### ISSUE TITLE
haskell_doc should support haskell_proto_library

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#1030]
rules_haskell rev dabf7afd9d5dc622d187a71169e2bb6b54ca3a8f
bazel version 0.28
--------------------------------------------------------
I have a build file something like:
```
load("@io_tweag_rules_haskell//haskell:haskell.bzl", 
    "haskell_library",
    "haskell_proto_library",
    "haskell_doc")

proto_library(
    name = "hello_world_proto",
    srcs = ["hello_world.proto"],
)

haskell_proto_library(
    name = "hello_world_haskell_proto",
    deps = [
        ":hello_world_proto",
    ],
)

kitty_haskell_library(
    name = "hello_world_haskell",
    srcs = ["HelloWorld.hs"],  # Just imports the proto and does something trivial
    deps = [
        ":hello_world_haskell_proto",
        "//ghc_pkgs:base",
        "//ghc_pkgs:lens",
        "//ghc_pkgs:text",
    ],
)

# Haddocks version A: depend on just the haskell_library
haskell_doc(
    name = "haddocks_a",
    deps = [
        ":hello_world_haskell",
    ],
)

# Haddocks version B: depend on both haskell_library and haskell_proto_library
haskell_doc(
    name = "haddocks_b",
    deps = [
        ":hello_world_haskell",
        ":hello_world_haskell_proto",
    ],
)
```

It's a bazel `proto_library` which a `haskell_proto_library` depends on, and a normal `haskell_library` which imports the `haskell_proto_library`.

When I try to generate haddocks depending only on the `haskell_library` I get a warning that the proto is not in scope:
```
samples/protobufs/HelloWorld.hs:1:1:
    Could not find link destinations for:

	- Proto.Samples.Protobufs.HelloWorld.HelloWorld
```

When I try to generate haddocks depending also on the `haskell_proto_library`, I get a `rules_haskell` error something like:
```
ERROR: /home/greg/the_project/samples/protobufs/BUILD.bazel:38:1: in haskell_doc rule //samples/protobufs:haddocks_b: 
Traceback (most recent call last):
	File "/home/greg/the_project/samples/protobufs/BUILD.bazel", line 38
		haskell_doc(name = 'haddocks_b')
	File "/home/greg/.cache/bazel/_bazel_greg/105d860db94dde3a6fc3b4a248924017/external/io_tweag_rules_haskell/haskell/haddock.bzl", line 254, in _haskell_doc_rule_impl
		haddock_dict[package_id]
key None not found in dictionary
```
I assume that this is unsupported functionality.

This is important to us adopting `haskell_proto_library` because we hacked haddock to error on warnings.

**Comment by ghorn** [comment]
Any estimates on how hard this would be? This is blocking the use of protobufs for us.

**Comment by Profpatsch** [comment]
cc @flokli @guibou

**Comment by guibou** [comment]
At least: #1108 show the issue.

**Comment by flokli** [comment]
GitHub autoclosed this due to the description in #1108, but it's not yet fixed, so reopening.

**Comment by aherrmann** [comment]
This seems to still be an issue.
```
$ bazel test //tests/haddock_protobuf:all
...
INFO: From HaskellHaddock //tests/haddock_protobuf:hello_world_haskell:
Warning: HelloWorld: could not find link destinations for:

        - Proto.Tests.HaddockProtobuf.HelloWorld.Person
...
```
And the generated haddocs don't include the protobuf symbols.
