### ISSUE TITLE
Error building `path-io` package.

### ISSUE THREAD

**Issue by joneshf** [tweag/rules_haskell#1248]
**Describe the bug**

There appears to be an error when building the [`path-io`](https://hackage.haskell.org/package/path-io) package: `hGetContents: invalid argument (invalid byte sequence)`. When I've seen this failure in the past, it appears to be a locale issue. It might not be a locale issue, though. I'm not sure how to fix this issue, in any case. Any ideas how to fix things so `path-io` might compile?

**To Reproduce**

I've put together a minimal reproduction at [joneshf/rules_haskell_invalid_byte_sequence](https://github.com/joneshf/rules_haskell_invalid_byte_sequence). For posterity, the files included are:

<details>
<summary>BUILD.bazel</summary>

```bazel
load(
    "@rules_haskell//haskell:defs.bzl",
    "haskell_library",
)

haskell_library(
    deps = [
        "@stackage//:path-io",
    ],
    name = "invalid_byte_sequence",
)
```
</details>

<details>
<summary>WORKSPACE.bazel</summary>

```bazel
workspace(
    name = "rules_haskell_invalid_byte_sequence",
)

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "rules_haskell",
    sha256 = "5778f69448b775ee96ee26439e3624db540a9e515caa46aa2eff99f9c91ab849",
    strip_prefix = "rules_haskell-1fedad7e64ea00ecf1bcb4be70ca51a11dc48312",
    urls = [
        "https://github.com/tweag/rules_haskell/archive/1fedad7e64ea00ecf1bcb4be70ca51a11dc48312.zip",
    ],
)

load(
    "@rules_haskell//haskell:repositories.bzl",
    "rules_haskell_dependencies",
)

rules_haskell_dependencies()

load(
    "@rules_haskell//haskell:toolchain.bzl",
    "rules_haskell_toolchains",
)

rules_haskell_toolchains(
    version = "8.8.2",
)

load(
    "@rules_haskell//haskell:cabal.bzl",
    "stack_snapshot",
)

stack_snapshot(
    name = "stackage",
    packages = [
        "path-io",
    ],
    snapshot = "lts-15.0",
)
```
</details>

Running `bazel build` shows the failure:

```console
$ bazel build //...
DEBUG: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/rules_haskell/haskell/cabal.bzl:1062:13: Stack version not recent enough. Downloading a newer version...
WARNING: Download from https://mirror.bazel.build/github.com/google/protobuf/archive/v3.11.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed 3 targets (1 packages loaded, 3 targets configured).
INFO: Found 3 targets...
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/stackage/BUILD.bazel:185:1: HaskellCabalLibrary @stackage//:path-io failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:path-io path-io-1.6.0 true external/stackage/path-io-1.6.0/Setup.hs external/stackage/path-io-1.6.0 ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/22/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 170, in <module>
    run([runghc, setup, "haddock", "--verbose=0", "--builddir=" + distdir])
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/22/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/22/execroot/rules_haskell_invalid_byte_sequence/external/rules_haskell_ghc_linux_amd64/bin/runghc', '/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/22/execroot/rules_haskell_invalid_byte_sequence/external/stackage/path-io-1.6.0/Setup.hs', 'haddock', '--verbose=0', '--builddir=/tmp/tmputn68mya']' returned non-zero exit status 1.
haddock: internal error: /tmp/tmputn68mya/doc/html/path-io/haddock-response300-1.txt: hGetContents: invalid argument (invalid byte sequence)
INFO: Elapsed time: 6.580s, Critical Path: 6.27s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Expected behavior**

Things should build like normal.

**Environment**
- OS name + version:
    ```console
    $ uname --all
    Linux arch-laptop-novo 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux
    ```
- Bazel version:
    ```console
    $ bazel version                                                 
    Build label: 2.1.0
    Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Fri Feb 7 13:01:04 2020 (1581080464)
    Build timestamp: 1581080464
    Build timestamp as int: 1581080464
    ```
- Version of the rules:
    git commit `1fedad7e64ea00ecf1bcb4be70ca51a11dc48312`

**Additional context**
I've tried this on a couple of stack snapshots, same result.

If I run `stack build` with a similar setup (resolver, dependencies, etc.), there's no issue compiling `path-io`.

**Comment by regnat** [comment]
This indeed looks like a locale issue (I guess `haddock` prints some warning that contains unicode characters, but the locale in the build sandbox isn't unicode aware).

You can try with `--action_env LC_ALL=C.UTF-8` to force a valid UTF-8 locale.

If you're using a Nix-provided bazel, `--action_env LOCALE_ARCHIVE` might help too as the glibc from Nixpkgs uses the `LOCALE_ARCHIVE` environment variable to find the locale database.

**Comment by joneshf** [comment]
Thanks for the suggestion!

Unfortunately, that doesn't seem to fix the issue. It still seems to fail with the same error:
```console
$ bazel build --action_env LC_ALL=C.UTF-8 //...
DEBUG: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/rules_haskell/haskell/cabal.bzl:1062:13: Stack version not recent enough. Downloading a newer version...
INFO: Analyzed 3 targets (4 packages loaded, 149 targets configured).
INFO: Found 3 targets...
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/stackage/BUILD.bazel:185:1: HaskellCabalLibrary @stackage//:path-io failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:path-io path-io-1.6.0 true external/stackage/path-io-1.6.0/Setup.hs external/stackage/path-io-1.6.0 ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/23/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 170, in <module>
    run([runghc, setup, "haddock", "--verbose=0", "--builddir=" + distdir])
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/23/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/23/execroot/rules_haskell_invalid_byte_sequence/external/rules_haskell_ghc_linux_amd64/bin/runghc', '/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/23/execroot/rules_haskell_invalid_byte_sequence/external/stackage/path-io-1.6.0/Setup.hs', 'haddock', '--verbose=0', '--builddir=/tmp/tmpnyuj6pql']' returned non-zero exit status 1.
haddock: internal error: /tmp/tmpnyuj6pql/doc/html/path-io/haddock-response300-1.txt: hGetContents: invalid argument (invalid byte sequence)
INFO: Elapsed time: 7.233s, Critical Path: 6.47s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I also tried `repo_env`, in case that would do anything. No dice:
```console
$ bazel build --action_env LC_ALL=C.UTF-8 --repo_env LC_ALL=C.UTF-8 //...
INFO: Build options --action_env and --repo_env have changed, discarding analysis cache.
DEBUG: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/rules_haskell/haskell/cabal.bzl:1062:13: Stack version not recent enough. Downloading a newer version...
INFO: Analyzed 3 targets (30 packages loaded, 1928 targets configured).
INFO: Found 3 targets...
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/stackage/BUILD.bazel:185:1: HaskellCabalLibrary @stackage//:path-io failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:path-io path-io-1.6.0 true external/stackage/path-io-1.6.0/Setup.hs external/stackage/path-io-1.6.0 ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/24/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 170, in <module>
    run([runghc, setup, "haddock", "--verbose=0", "--builddir=" + distdir])
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/24/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/24/execroot/rules_haskell_invalid_byte_sequence/external/rules_haskell_ghc_linux_amd64/bin/runghc', '/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/24/execroot/rules_haskell_invalid_byte_sequence/external/stackage/path-io-1.6.0/Setup.hs', 'haddock', '--verbose=0', '--builddir=/tmp/tmp1th4l21u']' returned non-zero exit status 1.
haddock: internal error: /tmp/tmp1th4l21u/doc/html/path-io/haddock-response300-1.txt: hGetContents: invalid argument (invalid byte sequence)
INFO: Elapsed time: 138.457s, Critical Path: 7.20s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I'm using the non-nix stuff.

**Comment by aherrmann** [comment]
@joneshf Thanks for providing a reproduction. Unfortunately, I was unable to reproduce the issue on Ubuntu 19.10 (not using Nix).

I ran `bazel build --action_env LC_ALL=C.UTF-8` with `-s` to confirm that Bazel is actually passing the variable forward to the Cabal build action. It turns out, it is not, see https://github.com/bazelbuild/rules_go/issues/2057. The build action is passed `LANG=C.UTF-8` instead, which we define in `rules_haskell`.

You can use the following patch to your reproduction in order to test if setting `LC_ALL` resolves the issue:

```patch
diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
index 5a57cde..5ac4dbc 100644
--- a/WORKSPACE.bazel
+++ b/WORKSPACE.bazel
@@ -14,6 +14,8 @@ http_archive(
     urls = [
         "https://github.com/tweag/rules_haskell/archive/1fedad7e64ea00ecf1bcb4be70ca51a11dc48312.zip",
     ],
+    patches = ["//:rules_haskell.patch"],
+    patch_args = ["-p1"],
 )

 load(
diff --git a/rules_haskell.patch b/rules_haskell.patch
new file mode 100644
index 0000000..e4b5449
--- /dev/null
+++ b/rules_haskell.patch
@@ -0,0 +1,12 @@
+diff --git a/haskell/private/context.bzl b/haskell/private/context.bzl
+index 4227ebf7..37e45ca5 100644
+--- a/haskell/private/context.bzl
++++ b/haskell/private/context.bzl
+@@ -27,6 +27,7 @@ def haskell_context(ctx, attr = None):
+
+     env = {
+         "LANG": toolchain.locale,
++        "LC_ALL": toolchain.locale,
+     }
+
+     if toolchain.locale_archive != None:
```

**Comment by joneshf** [comment]
Thanks for the suggestion, and thanks for trying to reproduce it on Ubuntu!

Unfortunately, that didn't seem to fix it either:
```console
$ bazel build //...                                                
Starting local Bazel server and connecting to it...
DEBUG: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/rules_haskell/haskell/cabal.bzl:1062:13: Stack version not recent enough. Downloading a newer version...
INFO: Analyzed 3 targets (30 packages loaded, 1928 targets configured).
INFO: Found 3 targets...
INFO: Deleting stale sandbox base /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox
INFO: From HaskellCabalLibrary @stackage//:dlist:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:integer-logarithms:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:unix-compat:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:tagged:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:random:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:base-compat:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:th-abstraction:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:base-orphans:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:hashable:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:exceptions:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:primitive:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:temporary:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:time-compat:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:uuid-types:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:scientific:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:unordered-containers:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:attoparsec:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:vector:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:aeson:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
INFO: From HaskellCabalLibrary @stackage//:path:
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/external/stackage/BUILD.bazel:185:1: HaskellCabalLibrary @stackage//:path-io failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:path-io path-io-1.6.0 true external/stackage/path-io-1.6.0/Setup.hs external/stackage/path-io-1.6.0 ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Traceback (most recent call last):
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/21/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 170, in <module>
    run([runghc, setup, "haddock", "--verbose=0", "--builddir=" + distdir])
  File "/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/21/execroot/rules_haskell_invalid_byte_sequence/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/21/execroot/rules_haskell_invalid_byte_sequence/external/rules_haskell_ghc_linux_amd64/bin/runghc', '/home/joneshf/.cache/bazel/_bazel_joneshf/172f5bcde64060fcaf156d4c2ba2e2c4/sandbox/linux-sandbox/21/execroot/rules_haskell_invalid_byte_sequence/external/stackage/path-io-1.6.0/Setup.hs', 'haddock', '--verbose=0', '--builddir=/tmp/tmpjyrnnwkc']' returned non-zero exit status 1.
haddock: internal error: /tmp/tmpjyrnnwkc/doc/html/path-io/haddock-response300-1.txt: hGetContents: invalid argument (invalid byte sequence)
INFO: Elapsed time: 420.661s, Critical Path: 279.63s
INFO: 20 processes: 20 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Could this be something on my system that needs to change? Here's the output of `locale`, in case it provides any insight:
```console
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by aherrmann** [comment]
@joneshf You said that you are on Arch Linux, correct? I've found some references that Arch Linux doesn't support `C.UTF-8`, e.g. https://github.com/electron-userland/electron-builder/issues/2340. However, the most recent I found is still two years old. Do you know the state of `C.UTF-8` on Arch?

It's worth a shot if `en_US.UTF-8` works for you. You can try with the following patch on top of your repro
```patch
diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
index 5a57cde..5ac4dbc 100644
--- a/WORKSPACE.bazel
+++ b/WORKSPACE.bazel
@@ -14,6 +14,8 @@ http_archive(
     urls = [
         "https://github.com/tweag/rules_haskell/archive/1fedad7e64ea00ecf1bcb4be70ca51a11dc48312.zip",
     ],
+    patches = ["//:rules_haskell.patch"],
+    patch_args = ["-p1"],
 )

 load(
diff --git a/rules_haskell.patch b/rules_haskell.patch
new file mode 100644
index 0000000..e29510a
--- /dev/null
+++ b/rules_haskell.patch
@@ -0,0 +1,13 @@
+diff --git a/haskell/toolchain.bzl b/haskell/toolchain.bzl
+index b57bbc3c..32e4acfa 100644
+--- a/haskell/toolchain.bzl
++++ b/haskell/toolchain.bzl
+@@ -228,7 +228,7 @@ _haskell_toolchain = rule(
+             doc = "Whether GHC was linked statically.",
+         ),
+         "locale": attr.string(
+-            default = "C.UTF-8",
++            default = "en_US.UTF-8",
+             doc = "Locale that will be set during compiler invocations.",
+         ),
+         "locale_archive": attr.label(
```

**Comment by joneshf** [comment]
:tada: :tada: :tada: That seems to work! Thanks!

Yes, I'm on Arch Linux. It doesn't surprise me that Arch Linux would be the root of the woes. What's weird is that if I ask which locales are available, it says `C` is one of them:
```console
$ locale --all-locales
C
en_US
en_US.iso88591
en_US.utf8
POSIX
```

I also could've sworn I ran into locale issues with something else and was able to use `LANG=C.UTF-8` or `LC_ALL=C.UTF-8` to address them. Maybe not. It's been a while.

In any case, this gets me moving forward. What's the next step? I assume the default locale shouldn't actually change. Maybe a PR to allow setting the `locale` attribute if you're not using the nix stuff?

**Comment by aherrmann** [comment]
Great to hear that it works now.

`C` and `C.UTF-8` are two separate locales. E.g. on Ubuntu they are listed separately
```
$ locale --all-locales
C
C.UTF-8
...
```

> What's the next step? I assume the default locale shouldn't actually change. Maybe a PR to allow setting the locale attribute if you're not using the nix stuff?

Yes, making this more easily configurable seems like a sensible solution. The `haskell_toolchain` rule already takes the locale as an attribute. We just need to expose it through the bindist wrapper.

**Comment by mboes** [comment]
We could also add an extra entry in the troubleshooting section.

**Comment by Profpatsch** [comment]
It surprises me that Archlinux of all distros doesn’t support `C.UTF-8` yet. oO

**Comment by joneshf** [comment]
> `C` and `C.UTF-8` are two separate locales.

Well, that explains it!

> Yes, making this more easily configurable seems like a sensible solution. The `haskell_toolchain` rule already takes the locale as an attribute. We just need to expose it through the bindist wrapper.

> We could also add an extra entry in the troubleshooting section.

I'll try to throw a PR together for these two things.

**Comment by joneshf** [comment]
Thanks everyone for your help!
