### ISSUE TITLE
hsc C compilation is incompatible with --nobuild_runfile_links

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#1312]
**Describe the bug**
`bazel build --nobuild_runfile_links` on a Haskell target using `.hsc` files fails with an 

**To Reproduce**
`bazel build --nobuild_runfile_links //:some_target`

`some_target` just needs to be a .hsc file. I can produce a repro if necessary. It seems all other rules work fine with this option, just not the hsc C compilation step. hsc2hs seems to work fine, too, but it also produces a .c file that needs to be compiled.

```
Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 368, in <module>
    Main()
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 272, in Main
    module_space = FindModuleSpace()
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 111, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python
compiling bazel-out/k8-fastbuild/bin/external/haskell_clock_94755854/_hsc/clock/System/Clock_hsc_make.c failed (exit code 1)
command was: bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python -c bazel-out/k8-fastbuild/bin/external/haskell_clock_94755854/_hsc/clock/System/Clock_hsc_make.c -o bazel-out/k8-fastbuild/bin/external/haskell_clock_94755854/_hsc/clock/System/Clock_hsc_make.o -fno-stack-protector -iquote external/haskell_clock_94755854 -iquote bazel-out/k8-fastbuild/bin/external/haskell_clock_94755854 -isystem external/haskell_clock_94755854/cbits -isystem bazel-out/k8-fastbuild/bin/external/haskell_clock_94755854/cbits -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -include bazel-out/host/bin/external/rules_haskell_ghc_linux_amd64/base_version_macros.h -I/usr/local/home/iphydf/.cache/bazel/_bazel_iphydf/87c462f2b35b8d3dfe6f6c21308fd127/execroot/toktok/external/rules_haskell_ghc_linux_amd64/bin/../lib/include/
Target @haskell_clock_94755854//:clock failed to build
```

**Expected behavior**
Build should succeed like this:
```
Target @haskell_clock_94755854//:clock up-to-date:
  bazel-bin/external/haskell_clock_94755854/libHSexternalZShaskellZUclockZU94755854ZSclock.a
  bazel-bin/external/haskell_clock_94755854/libHSexternalZShaskellZUclockZU94755854ZSclock-ghc8.6.5.so
```

**Environment**
 - OS name + version: Debian GNU/Linux 9 (stretch)
 - Bazel version: 3.0.0
 - Version of the rules: c625c53c3fe6644abb366bd868051d9e82f2a204

**Additional context**
`--nobuild_runfile_links` is part of `--remote_download_minimal`, which is very useful for speeding up builds that use RBE.

**Comment by iphydf** [comment]
This is still not working:

```
Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 388, in <module>
    Main()
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 288, in Main
    module_space = FindModuleSpace()
  File "bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python", line 118, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
```

**Comment by aherrmann** [comment]
This seems to be resolved. At least the following passes
```
$ bazel build --nobuild_runfile_links //tests/hsc:hsc
```
