### ISSUE TITLE
trouble creating static binary

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1412]
**Describe the bug**

I am trying to compile some static haskell binaries via `bazel build ...` but not sure how to fix:
```
A clear and concise description of what the bug is.
INFO: Invocation ID: 954278b3-1580-4df0-bab6-fe81ec0a10d4
INFO: Analyzed target //simwork/core:core (69 packages loaded, 9249 targets configured).
INFO: Found 1 target...
ERROR: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/external/hackage/BUILD.bazel:678:22: HaskellCabalLibrary @hackage//:basement failed (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace && \
  exec env - \
    LANG=C.UTF-8 \
    PATH=external/llvm_9/bin:/nix/store/xp07n0nk8j4gvycsvl2bf3s5c6cbalim-posix-toolchain/bin \
    TMPDIR=/tmp \
  /home/teto/.cache/bazel/_bazel_teto/install/94ef554a9b55bbbc23412bddca7b843c/linux-sandbox -t 15 -w /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace -w /tmp -w /dev/shm -D -- bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper lib:basement basement-0.0.11 true external/hackage/basement-0.0.11/Setup.hs external/hackage/basement-0.0.11 bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/_install/basement-0.0.11.conf.d '' '--flags=' '--ghc-option=-optl-no-pie' '--ghc-option=-w' '--ghc-option=-optF=-w' '--ghc-option=-fPIC' '--ghc-option=-fexternal-dynamic-refs' '--hsc2hs-option=--lflag=-static' --) linux-sandbox failed: error executing command 
  (cd /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace && \
  exec env - \
    LANG=C.UTF-8 \
    PATH=external/llvm_9/bin:/nix/store/xp07n0nk8j4gvycsvl2bf3s5c6cbalim-posix-toolchain/bin \
    TMPDIR=/tmp \
  /home/teto/.cache/bazel/_bazel_teto/install/94ef554a9b55bbbc23412bddca7b843c/linux-sandbox -t 15 -w /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace -w /tmp -w /dev/shm -D -- bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper lib:basement basement-0.0.11 true external/hackage/basement-0.0.11/Setup.hs external/hackage/basement-0.0.11 bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/_install/basement-0.0.11.conf.d '' '--flags=' '--ghc-option=-optl-no-pie' '--ghc-option=-w' '--ghc-option=-optF=-w' '--ghc-option=-fPIC' '--ghc-option=-fexternal-dynamic-refs' '--hsc2hs-option=--lflag=-static' --)
src/main/tools/linux-sandbox.cc:156: linux-sandbox-pid1 has PID 30144
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
src/main/tools/linux-sandbox-pid1.cc:176: working dir: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace
src/main/tools/linux-sandbox-pid1.cc:208: writable: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace
sr
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lm
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lrt
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -ldl
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
linking ../../../bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/tmpa6e9j0a7/build/Basement/Terminal/Size_hsc_make.o failed (exit code 1)
command was: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cc_wrapper-python ../../../bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/tmpa6e9j0a7/build/Basement/Terminal/Size_hsc_make.o ../../../bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/tmpa6e9j0a7/build/Basement/Terminal/Size_hsc_utils.o -o ../../../bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/tmpa6e9j0a7/build/Basement/Terminal/Size_hsc_make -L/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/base-4.13.0.0 -L/nix/store/8davc1jj988yjzgrc4nlgslz0q6lwdna-musl-iconv-1.1.24/lib -Wl,-R,/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/base-4.13.0.0 -Wl,-R,/nix/store/8davc1jj988yjzgrc4nlgslz0q6lwdna-musl-iconv-1.1.24/lib -L/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/integer-gmp-1.0.2.0 -L/nix/store/pmail2mg8ybrygr1m3izzc0klvr1mgkz-gmp-6.1.2/lib -Wl,-R,/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/integer-gmp-1.0.2.0 -Wl,-R,/nix/store/pmail2mg8ybrygr1m3izzc0klvr1mgkz-gmp-6.1.2/lib -lgmp -L/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/ghc-prim-0.5.3 -Wl,-R,/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/ghc-prim-0.5.3 -L/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/rts -L/nix/store/02a76sbyi6k112ha6nyvs02kpxka732b-libffi-3.3/lib -Wl,-R,/nix/store/5gdgssa0mrcmqd76d2wix4b1yivp2vd3-ghc-8.8.1/lib/ghc-8.8.1/rts -Wl,-R,/nix/store/02a76sbyi6k112ha6nyvs02kpxka732b-libffi-3.3/lib -lm -lrt -ldl -lffi -static
Traceback (most recent call last):
  File "/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 194, in <module>
    run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  File "/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/nix/store/f87w21b91cws0wbsvyfn5vnlyv491czi-python3-3.8.3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/external/rules_haskell_ghc_nixpkgs/bin/runghc', '/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/external/hackage/basement-0.0.11/Setup.hs', 'build', '--verbose=0', '--builddir=/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/tmpa6e9j0a7']' returned non-zero exit status 1.
src/main/tools/linux-sandbox-pid1.cc:436: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:456: child exited with code 1
src/main/tools/linux-sandbox.cc:206: child exited normally with exitcode 1
Target //simwork/core:core failed to build
ERROR: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/external/hackage/BUILD.bazel:471:22 HaskellCabalLibrary @hackage//:basement failed (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace && \
  exec env - \
    LANG=C.UTF-8 \
    PATH=external/llvm_9/bin:/nix/store/xp07n0nk8j4gvycsvl2bf3s5c6cbalim-posix-toolchain/bin \
    TMPDIR=/tmp \
  /home/teto/.cache/bazel/_bazel_teto/install/94ef554a9b55bbbc23412bddca7b843c/linux-sandbox -t 15 -w /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace -w /tmp -w /dev/shm -D -- bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper lib:basement basement-0.0.11 true external/hackage/basement-0.0.11/Setup.hs external/hackage/basement-0.0.11 bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/_install/basement-0.0.11.conf.d '' '--flags=' '--ghc-option=-optl-no-pie' '--ghc-option=-w' '--ghc-option=-optF=-w' '--ghc-option=-fPIC' '--ghc-option=-fexternal-dynamic-refs' '--hsc2hs-option=--lflag=-static' --) linux-sandbox failed: error executing command 
  (cd /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace && \
  exec env - \
    LANG=C.UTF-8 \
    PATH=external/llvm_9/bin:/nix/store/xp07n0nk8j4gvycsvl2bf3s5c6cbalim-posix-toolchain/bin \
    TMPDIR=/tmp \
  /home/teto/.cache/bazel/_bazel_teto/install/94ef554a9b55bbbc23412bddca7b843c/linux-sandbox -t 15 -w /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/sandbox/linux-sandbox/98/execroot/toplevel_workspace -w /tmp -w /dev/shm -D -- bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper lib:basement basement-0.0.11 true external/hackage/basement-0.0.11/Setup.hs external/hackage/basement-0.0.11 bazel-out/k8-fastbuild/bin/external/hackage/basement-0.0.11/_install/basement-0.0.11.conf.d '' '--flags=' '--ghc-option=-optl-no-pie' '--ghc-option=-w' '--ghc-option=-optF=-w' '--ghc-option=-fPIC' '--ghc-option=-fexternal-dynamic-refs' '--hsc2hs-option=--lflag=-static' --)
```
**To Reproduce**

Sadly I can't share the repository but I can share the bazel part, mostly copied from the rules_haskell doc, using the staticHaskell from https://github.com/nh2/static-haskell-nix
```
    rules_haskell_dependencies()
    pedantic_compiler_flags = [
        "-Wall",
        "-Werror",
        "-Wcompat",
        "-Wincomplete-record-updates",
        "-Wincomplete-uni-patterns",
        "-Wredundant-constraints",
        "-Wnoncanonical-monad-instances",
    ]
    default_flags = [
        "-fdiagnostics-color=always",
        "-freduction-depth=0",
        "-fwrite-ide-info",
        "-hiedir=.hie"
    ]

    haskell_register_ghc_nixpkgs(
        repositories = {"nixpkgs": "@buildlib//nix:default.nix"},
        attribute_path = "staticHaskell.ghc",
        version = "8.8.1",
        nix_file_deps = nixpkgs_deps,
        compiler_flags_select = {
            "@buildlib//:pedantic": default_flags + pedantic_compiler_flags,
            "@buildlib//:non_pedantic": default_flags,
            "//conditions:default": default_flags + pedantic_compiler_flags,
        },
        static_runtime = True,
        fully_static_link = True,
        **kwargs
    )

    nixpkgs_cc_configure(
        # The `staticHaskell` attribute in the previous example exposes the
        # Musl-backed `cc` and `binutils` derivations already, so it's just a
        # matter of exposing them to nixpkgs_cc_configure.
        nix_file_content = """
            with import <nixpkgs> { config = {}; overlays = []; }; buildEnv {
            name = "bazel-cc-toolchain";
            paths = [ staticHaskell.stdenv.cc staticHaskell.binutils ];
            }
        """,
        **(nixpkgs_package_args())
    )

```

**Environment**
 - OS name + version: nixos unstable
 - Bazel version: 3.3.1
 - Version of the rules: current master aabeedc

**Comment by Profpatsch** [comment]
Sorry for the oversight, have you been able to fix this problem in the meantime? If so, what was the issue? If not, any new information that can help us fix it?

**Comment by teto** [comment]
I've changed my approach so instead of replacing my old toolchain I would like to keep the old one and add the new static one. 
I dont know yet if I would just test alternatively each toolchain for the whole project or just the static toolchain for some specific targets (e.g., binaries to be embedded in containers).

Now I wonder if I could mark the packages with `features = ["fully_static_link"]` and have it select one toolchain rather than the other based on this (or any other way to select a toolchain for certain packages).
The approach may end up compiling twcie (dynamic/static) several components but I would like to give it a try.

**Comment by aherrmann** [comment]
There are a few ways to switch between these toolchains.

If you would like to switch between the toolchains globally, i.e. build the whole project with the same toolchain, then this could be implemented with an `if` condition in the `WORKSPACE` file to decide which toolchain to register. The condition to switch on could be determined by a repository rule that, e.g. reads some env-var to configure the project between different modes. An example can be seen in rules_haskell [here](https://github.com/tweag/rules_haskell/blob/a2101992ea0e5271f9114431c3e15cafe1e16752/tools/os_info.bzl) and [here](https://github.com/tweag/rules_haskell/blob/a2101992ea0e5271f9114431c3e15cafe1e16752/WORKSPACE#L497) to switch between whether the project is being built in a Nix shell or not. I expect this to be the easier option if it is sufficient for your use-case.

If instead you would like to only build some targets with a fully static toolchain and others with a regular toolchain, then you will have to look into Bazel's [platforms and toolchains](https://docs.bazel.build/versions/master/platforms-intro.html) mechanism. You'll have to define a custom platform for fully static mode and then define a dedicated toolchain for that platform. The recently added [cross-compilation example](https://github.com/tweag/rules_haskell/blob/a2101992ea0e5271f9114431c3e15cafe1e16752/examples/arm/WORKSPACE) performs a similar setup. Note, how it configures two versions of the cc and haskell toolchains with different platform constraints. You can then use Bazel's [configuration transitions](https://docs.bazel.build/versions/master/platforms-intro.html#transitions) to specify which targets should be built for which platform. I expect that setting this up will be a bit more involved.

---

Regarding the original error.
```
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lm
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lrt
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -ldl
/nix/store/ydk00ssq4fyx78rpmdmq1hcmz0iw575f-binutils-2.31.1/bin/ld: cannot find -lc
```
Perhaps some library search path is not configured correctly? AFAIK musl doesn't have separate `libm`, `librt`, ..., but only a single `libc`. Though, it might provide empty dummies for the former to avoid such linker issues. Have you compared your setup to this example project: https://github.com/lunaris/minirepo?

**Comment by teto** [comment]
thanks for the detailed answer. The minrepo contains interesting bits to me like https://github.com/lunaris/minirepo/blob/58c3a67a09e97d22995380bb97f9e8cef6215fa9/bazel/repository/haskell.bzl#L190 .

Because I am a masochist, I tried the 2nd way and I have a question that may or may not be out of scope so feel free to redirect me to bazel-discuss.


```
constraint_setting(name = "nova_static")

constraint_value(
    name = "build-static",
    constraint_setting = ":nova_static",
    visibility = ["//visibility:public"],
)

platform(
    name = "linux_x86-static",    # name is not the best but we only compile on linux64
    constraint_values = [
        ":build-static",
    ],
    parents = ["@io_tweag_rules_nixpkgs//nixpkgs/platforms:host"],
    visibility = ["//visibility:public"],
)
```

I have this binary which is the only target for which I have  added the new constraint
```
nova_haskell_binary(
    name = "result-store",
   ...
    exec_compatible_with = [
        "@buildlib//:build-static"
    ],
)
```
and then I have been trying to build that one with `--toolchain_resolution_debug` to understand what's going on:
```
(ins)➜ bazel build //simwork/result-store --toolchain_resolution_debug 
INFO: Invocation ID: e872ce85-dfd5-43c8-b652-3e96f066b634
INFO: Build option --platforms has changed, discarding analysis cache.
INFO: ToolchainResolution: Removed execution platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host from available execution platforms, it is missing constraint @buildlib//:build-static
INFO: ToolchainResolution:   Type @rules_sh//sh/posix:toolchain_type: target platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: No toolchains found.
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: Rejected toolchain @nixpkgs_config_cc//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:     Type @rules_haskell//haskell:toolchain: target @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: Rejected toolchain @ghc-static_ghc_nixpkgs_haskell_toolchain//:toolchain-impl; mismatching values: build-static
INFO: ToolchainResolution:   Type @rules_haskell//haskell:toolchain: target platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: No toolchains found.
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: Rejected toolchain @nixpkgs_config_cc_musl//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: Rejected toolchain @nixpkgs_config_cc_musl//:cc-compiler-k8; mismatching values: build-static
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: Rejected toolchain @local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:   Type @bazel_tools//tools/cpp:toolchain_type: target platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host: No toolchains found.
INFO: ToolchainResolution: Removed execution platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host from available execution platforms, it is missing constraint @buildlib//:build-static
ERROR: While resolving toolchains for target //simwork/result-store:result-store: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type
ERROR: Analysis of target '//simwork/result-store:result-store' failed; build aborted: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type
INFO: Elapsed time: 0.084s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 125 targets configured)
```
so this ^ is expected I think, next I try with my custom platform:
```
(ins)➜ bazel build //simwork/result-store --toolchain_resolution_debug  --platforms="@buildlib//:linux_x86-static"
INFO: Invocation ID: fe8ab5f4-f008-4016-9b0f-bb945078cb81
INFO: Build option --platforms has changed, discarding analysis cache.
INFO: ToolchainResolution: Removed execution platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host from available execution platforms, it is missing constraint @buildlib//:build-static
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @buildlib//:linux_x86-static: Rejected toolchain @nixpkgs_config_cc//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:   Type @rules_sh//sh/posix:toolchain_type: target platform @buildlib//:linux_x86-static: No toolchains found.
INFO: ToolchainResolution:   Type @rules_haskell//haskell:toolchain: target platform @buildlib//:linux_x86-static: No toolchains found.
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @buildlib//:linux_x86-static: Rejected toolchain @nixpkgs_config_cc_musl//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target @buildlib//:linux_x86-static: Rejected toolchain @local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: arm, android
INFO: ToolchainResolution:   Type @bazel_tools//tools/cpp:toolchain_type: target platform @buildlib//:linux_x86-static: No toolchains found.
INFO: ToolchainResolution: Removed execution platform @io_tweag_rules_nixpkgs//nixpkgs/platforms:host from available execution platforms, it is missing constraint @buildlib//:build-static
ERROR: While resolving toolchains for target //simwork/result-store:result-store: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type
ERROR: Analysis of target '//simwork/result-store:result-store' failed; build aborted: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type
INFO: Elapsed time: 0.074s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 126 targets configured)
```
The error  looks LGTM ? 
`'//simwork/result-store:result-store' failed; build aborted: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type`  but I dont call `sh_posix_configure` in my repo.

My understanding is that I need to have a sh toolchain that supports the constraint `@buildlib//:build-static` but I am not sure if I should declare if or if rules_nixpkgs should forward my arguments:

While I dont call sh_posix_configure, I do call 
```
    nixpkgs_cc_configure(
        name = "nixpkgs_config_cc_musl",
        # The `staticHaskell` attribute in the previous example exposes the
        # Musl-backed `cc` and `binutils` derivations already, so it's just a
        # matter of exposing them to nixpkgs_cc_configure.
        nix_file_content = """
            with import <nixpkgs> { config = {}; overlays = []; }; buildEnv {
            name = "bazel-cc-toolchain";
            paths = [ novaStaticHaskellPackages.stdenv.cc novaStaticHaskellPackages.binutils ];
            }
        """,
        exec_constraints = constraints,
        target_constraints = constraints,
        **(nixpkgs_package_args()),
    )
```
that I believe configure a rules_sh toolchain ? I wonder if there is a link with https://github.com/tweag/rules_nixpkgs/pull/163 ?

**Comment by aherrmann** [comment]
@teto Indeed, the POSIX toolchain is defined [along with the Haskell toolchain](https://github.com/tweag/rules_haskell/blob/a2101992ea0e5271f9114431c3e15cafe1e16752/haskell/nixpkgs.bzl#L339). So, it's implicit.

If I understand this right, then I think the issue here comes down to the difference between execution and target platform: Exection platform is the platform on which Bazel build actions are executed, target platform is the platform on which the generated binary is executed. With fully static linking the distinction is perhaps not so clear. But, I think it's best to think of `build-static` as a target platform constraint: The goal is that the resulting binary is fully statically linked and can be executed on a platform where no dynamic libraries are available.

The [`--platforms` flag](https://docs.bazel.build/versions/master/platforms.html#specifying-a-platform-for-a-build) already does the right thing and configures the target platform. The issue is the `exec_compatible_with` attribute. This tells Bazel that the build platform has to fulfill the static constraint. This particular error should go away if you remove the `exec_compatible_with` attribute on the `nova_haskell_binary`.

There is another attribute called `target_compatible_with`. It's part of Bazel's [target skipping](https://docs.bazel.build/versions/master/platforms.html#skipping-incompatible-targets) mechanism. It will tell Bazel to only build this target if the target platform fulfills the given constraints.

**Comment by teto** [comment]
hum rules_haskell doc says `target_compatible_with` should be supported but seems like it isn't  since it triggers `no such attribute 'target_compatible_with' in '_haskell_binary' rule` when I set it ?

Since I can only set `exec_compatible_with` for now, I have to set --host_platform otherwise bazel always selects the non-static toolchain.

When running `bazel run -s --script_path=./rs //simwork/result-store:result-store --toolchain_resolution_debug  --host_platform="@buildlib//:linux_x86-static"` it triggers errors in my own code so I'll look into it and see unti where I can go.

**Comment by aherrmann** [comment]
@teto The `target_compatible_with` attribute was only introduced in Bazel 4.0.0, which Bazel version are you using?

However, I think you don't need to set either attribute. Target skipping only tells Bazel which targets *not* to build in certain situations.

Concretely, I'd try to define
```
nova_haskell_binary(
    name = "result-store",
   ...
)
```
I.e. neither `exec_compatible_with` nor `target_compatible_with`.

Set the `target_constraints` of the toolchains to include the build-static constraint, I don't think it's needed on `exec_constraints`.

And then build it with
```
$ bazel build //simwork/result-store --platforms="@buildlib//:linux_x86-static"
```

**Comment by Xophmeister** [comment]
@teto Can this issue be closed, after following @aherrmann's suggestions?

**Comment by teto** [comment]
thanks for the helpful advice. Didn't succeed in the end, I might reopen next time I try.
