### ISSUE TITLE
Improve error message when Python is missing

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#1416]
**Is your feature request related to a problem? Please describe.**
Running any `bazel build` command on a fresh system with no Python, within a workspace that uses rules_haskell, will eventually yield an error of the form:
```
Repository rule _config_python3_toolchain defined at:
  /root/.cache/bazel/_bazel_root/abad448bf464eefeaf2734c3cc8cdd46/external/rules_haskell/haskell/ghc_bindist.bzl:598:44: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_haskell_python_local':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/abad448bf464eefeaf2734c3cc8cdd46/external/rules_haskell/haskell/ghc_bindist.bzl", line 562, column 32, in _configur
e_python3_toolchain_impl
                python3_path = _find_python(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/abad448bf464eefeaf2734c3cc8cdd46/external/rules_haskell/haskell/ghc_bindist.bzl", line 555, column 40, in _find_pyt
hon
                result = repository_ctx.execute([python, "--version"])
Error in execute: Argument 0 of execute is neither a path, label, nor string.
```

This message is not user-friendly. It does not immediately point to the root cause: that the `python` command simply does not exist on the current system.

**Describe the solution you'd like**
We could introduce a fall to `fail()` explaining that there is no `python` in the current `PATH`.

**Comment by facundominguez** [comment]
Fixed in #1529
