### ISSUE TITLE
ls_modules fails with multi-line id: entry

### ISSUE THREAD

**Issue by avdv** [tweag/rules_haskell#1453]
**Describe the bug**

Trying to compile a project, it fails with
```
Execution platform: @io_tweag_rules_nixpkgs//nixpkgs/platforms:host

Use --sandbox_debug to see verbose messages from the sandbox ls_modules failed: error executing command 
  (cd /home/claudio/.cache/bazel/_bazel_claudio/7cdb3fc80732e71fc5b4a8430d9ca82d/sandbox/linux-sandbox/14/execroot/treetide && \
  exec env - \
  bazel-out/host/bin/external/rules_haskell/haskell/ls_modules False bazel-out/k8-fastbuild/bin/treetide/haskell/extended/attoparsec/treetideZShaskellZSextendedZSattoparsecZSextended/_iface bazel-out/host/bin/external/rules_haskell_ghc_nixpkgs_haskell_toolchain/ghc-global-pkgdb bazel-out/k8-fastbuild/bin/treetide/haskell/extended/attoparsec/hidden-modules-extended bazel-out/k8-fastbuild/bin/treetide/haskell/extended/attoparsec/reexported-modules-extended bazel-out/k8-fastbuild/bin/treetide/haskell/extended/attoparsec/exposed-modules-extended)
Execution platform: @io_tweag_rules_nixpkgs//nixpkgs/platforms:host

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/claudio/.cache/bazel/_bazel_claudio/7cdb3fc80732e71fc5b4a8430d9ca82d/sandbox/linux-sandbox/14/execroot/treetide/bazel-out/host/bin/external/rules_haskell/haskell/ls_modules.runfiles/rules_haskell/haskell/private/ls_modules.py", line 32, in <module>
    ids = [line.split()[1] for line in f if line.startswith("id:")]
  File "/home/claudio/.cache/bazel/_bazel_claudio/7cdb3fc80732e71fc5b4a8430d9ca82d/sandbox/linux-sandbox/14/execroot/treetide/bazel-out/host/bin/external/rules_haskell/haskell/ls_modules.runfiles/rules_haskell/haskell/private/ls_modules.py", line 32, in <listcomp>
    ids = [line.split()[1] for line in f if line.startswith("id:")]
IndexError: list index out of range
```

This seems to be caused by this entry in `bazel-out/host/bin/external/rules_haskell_ghc_nixpkgs_haskell_toolchain/ghc-global-pkgdb`
```
---
name:                 data-default-instances-old-locale
version:              0.0.1
visibility:           public
id:
    data-default-instances-old-locale-0.0.1-26yQMJ7x0xCF8E8NsOHD2F

key:
    data-default-instances-old-locale-0.0.1-26yQMJ7x0xCF8E8NsOHD2F
...
```
Note, that the `id` entry is spread over two lines, probably because its value is too large to align nicely with the other columns and still fit within the  (preferred?) width.

**To Reproduce**

I could try minimize this and provide a reproducer, but I guess the case is quite clear. Say if you want me to provide one, please.

**Expected behavior**

I would expect the ls_modules to be able to parse the (compiler generated?) pkgdb file and not error out.

**Environment**
 - OS name + version: NixOS 20.09
 - Bazel version: 3.3.1
 - Version of the rules: 0.13

**Additional context**

**Comment by avdv** [comment]
Yes, 60 is the magic limit of a single line: https://hackage.haskell.org/package/Cabal-3.2.1.0/docs/src/Distribution.Fields.Pretty.html#renderField
```hs
renderField (Opts rann indent) fw (PrettyField ann name doc) =
    Block before after $ comments ++ lines'
  where
    comments = rann ann
    before = if null comments then NoMargin else Margin

    (lines', after) = case lines narrow of
        []           -> ([ name' ++ ":" ], NoMargin)
        [singleLine] | length singleLine < 60 --- HERE !!
                     -> ([ name' ++ ": " ++ replicate (fw - length name') ' ' ++ narrow ], NoMargin)
        _            -> ((name' ++ ":") : map indent (lines (PP.render doc)), Margin)
```

**Comment by avdv** [comment]
FWIW, I worked around using this patch:
```fix-ls-modules.patch
diff --git a/haskell/private/ls_modules.py b/haskell/private/ls_modules.py
index bb4d616a..50c2b263 100755
--- a/haskell/private/ls_modules.py
+++ b/haskell/private/ls_modules.py
@@ -29,7 +29,15 @@ results_file = sys.argv[6]
 with io.open(global_pkg_db_dump, "r", encoding='utf8') as f:
     names = [line.split()[1] for line in f if line.startswith("name:")]
     f.seek(0)
-    ids = [line.split()[1] for line in f if line.startswith("id:")]
+    ids = []
+    line = f.readline()
+    while line:
+        if line.startswith("id:"):
+            entry = line.rstrip().split(maxsplit=1)
+
+            ids.append(entry[1] if len(entry) > 1 else f.readline().strip())
+
+        line = f.readline()
 
     # A few sanity checks.
     assert len(names) == len(ids)

```
in my WORKSPACE file:
```bzl
http_archive(
    name = "rules_haskell",
    sha256 = "b4e2c00da9bc6668fa0404275fecfdb31beb700abdba0e029e74cacc388d94d6",
    strip_prefix = "rules_haskell-0.13",
    patch_args = ["-p1"],
    patches = ["//:fix-ls-modules.patch"],
    urls = ["https://github.com/tweag/rules_haskell/archive/v0.13.tar.gz"],
)
```

**Comment by Profpatsch** [comment]
Hi @avdv, would you mind opening a PR with your patch?

**Comment by aherrmann** [comment]
This looks like the same issue that is addressed by https://github.com/tweag/rules_haskell/pull/1396 . That PR got stuck on https://github.com/tweag/rules_haskell/pull/1396#issuecomment-660958851. I'll go ahead and merge it, we can still do the refactoring discussed in that comment in a follow-up.

**Comment by avdv** [comment]
Thanks, @aherrmann -- sorry I did not notice the PR before (usually I don't suck at searching).
