### ISSUE TITLE
Example (using start script) does not work on MacOS

### ISSUE THREAD

**Issue by BinaryHexer** [tweag/rules_haskell#1518]
**Describe the bug**
The start script does not setup the example correctly on MacOS.

**To Reproduce**
```sh
curl https://haskell.build/start | sh
```

**Expected behavior**
The example command `bazel run //:example` can run without error.

**Environment**
 - OS name + version: MacOS, 11.2.2 (20D80)
 - Bazel version: 3.3.1
 - Version of the rules: 0.13

**Additional context**

Default setup

```
INFO: Repository rules_haskell_ghc_darwin_amd64 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _ghc_bindist defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl:362:31: in <toplevel>
INFO: Repository 'rules_haskell_ghc_darwin_amd64' used the following cache hits instead of downloading the corresponding file.
 * Hash 'dfc1bdb1d303a87a8552aa17f5b080e61351f2823c2b99071ec23d0837422169' for https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-apple-darwin.tar.xz
If the definition of 'rules_haskell_ghc_darwin_amd64' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'rules_haskell_ghc_darwin_amd64':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl", line 292
		execute_or_fail_loudly(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: ./patch_bins
sed: bin/ghc: in-place editing only works for regular files
sed: bin/ghc-pkg: in-place editing only works for regular files
sed: bin/ghci: in-place editing only works for regular files
sed: bin/haddock: in-place editing only works for regular files
sed: bin/runghc: in-place editing only works for regular files
sed: bin/runhaskell: in-place editing only works for regular files
ERROR: /Users/vijayender.joshi/dev/temp/BUILD.bazel:29:15: //:example depends on @rules_haskell_ghc_darwin_amd64//:toolchain-impl in repository @rules_haskell_ghc_darwin_amd64 which failed to fetch. no such package '@rules_haskell_ghc_darwin_amd64//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl", line 292
		execute_or_fail_loudly(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: ./patch_bins
sed: bin/ghc: in-place editing only works for regular files
sed: bin/ghc-pkg: in-place editing only works for regular files
sed: bin/ghci: in-place editing only works for regular files
sed: bin/haddock: in-place editing only works for regular files
sed: bin/runghc: in-place editing only works for regular files
sed: bin/runhaskell: in-place editing only works for regular files
ERROR: Analysis of target '//:example' failed; build aborted: Analysis failed
INFO: Elapsed time: 72.470s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Setup using `--use-nix` option

```
INFO: Build options --host_platform and --platforms have changed, discarding analysis cache.
INFO: SHA256 (https://github.com/NixOS/nixpkgs/archive/19.03.tar.gz) = 4f9bb67ae2101cd9322eaf9743b57307bc50c5798c04c7bd245e6d2404ab3d62
INFO: Repository rules_haskell_ghc_nixpkgs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _nixpkgs_package defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:211:35: in <toplevel>
INFO: Repository rules_haskell_sh_posix_nixpkgs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _nixpkgs_package defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:211:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_haskell_ghc_nixpkgs':
   Platform is not supported: nix-build not found in PATH. See attribute fail_not_supported if you don't want to use Nix.
ERROR: /Users/vijayender.joshi/dev/temp/BUILD.bazel:29:15: Target '//:example' depends on toolchain '@rules_haskell_ghc_nixpkgs_haskell_toolchain//:toolchain-impl', which cannot be found: no such package '@rules_haskell_ghc_nixpkgs_haskell_toolchain//': no such package '@rules_haskell_ghc_nixpkgs//': Platform is not supported: nix-build not found in PATH. See attribute fail_not_supported if you don't want to use Nix.'
ERROR: Analysis of target '//:example' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.406s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 26 targets configured)
FAILED: Build did NOT complete successfully (19 packages loaded, 26 targets configured)
    Fetching @rules_haskell_ghc_nixpkgs_haskell_toolchain; Restarting. 9sINFO: Build options --host_platform and --platforms have changed, discarding analysis cache.
INFO: SHA256 (https://github.com/NixOS/nixpkgs/archive/19.03.tar.gz) = 4f9bb67ae2101cd9322eaf9743b57307bc50c5798c04c7bd245e6d2404ab3d62
INFO: Repository rules_haskell_ghc_nixpkgs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _nixpkgs_package defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:211:35: in <toplevel>
INFO: Repository rules_haskell_sh_posix_nixpkgs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _nixpkgs_package defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:211:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_haskell_ghc_nixpkgs':
   Platform is not supported: nix-build not found in PATH. See attribute fail_not_supported if you don't want to use Nix.
ERROR: /Users/vijayender.joshi/dev/temp/BUILD.bazel:29:15: Target '//:example' depends on toolchain '@rules_haskell_ghc_nixpkgs_haskell_toolchain//:toolchain-impl', which cannot be found: no such package '@rules_haskell_ghc_nixpkgs_haskell_toolchain//': no such package '@rules_haskell_ghc_nixpkgs//': Platform is not supported: nix-build not found in PATH. See attribute fail_not_supported if you don't want to use Nix.'
ERROR: Analysis of target '//:example' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.406s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 26 targets configured)
FAILED: Build did NOT complete successfully (19 packages loaded, 26 targets configured)
    Fetching @rules_haskell_ghc_nixpkgs_haskell_toolchain; Restarting. 9s
```

**Comment by aherrmann** [comment]
@BinaryHexer thank you for reporting! This looks like the same issue as reported in https://github.com/tweag/rules_haskell/issues/1442. Could you retry with the latest `start` script? https://github.com/tweag/rules_haskell/blob/master/start

**Comment by BinaryHexer** [comment]
I tried again with the script from `master`, but the result seems to be the same...

```
INFO: Repository rules_haskell_ghc_darwin_amd64 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _ghc_bindist defined at:
  /private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl:362:31: in <toplevel>
INFO: Repository 'rules_haskell_ghc_darwin_amd64' used the following cache hits instead of downloading the corresponding file.
 * Hash 'dfc1bdb1d303a87a8552aa17f5b080e61351f2823c2b99071ec23d0837422169' for https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-apple-darwin.tar.xz
If the definition of 'rules_haskell_ghc_darwin_amd64' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'rules_haskell_ghc_darwin_amd64':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl", line 292
		execute_or_fail_loudly(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: ./patch_bins
sed: bin/ghc: in-place editing only works for regular files
sed: bin/ghc-pkg: in-place editing only works for regular files
sed: bin/ghci: in-place editing only works for regular files
sed: bin/haddock: in-place editing only works for regular files
sed: bin/runghc: in-place editing only works for regular files
sed: bin/runhaskell: in-place editing only works for regular files
ERROR: /Users/vijayender.joshi/dev/temp/BUILD.bazel:29:15: //:example depends on @rules_haskell_ghc_darwin_amd64//:toolchain-impl in repository @rules_haskell_ghc_darwin_amd64 which failed to fetch. no such package '@rules_haskell_ghc_darwin_amd64//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/ghc_bindist.bzl", line 292
		execute_or_fail_loudly(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_vijayender.joshi/5b34e9bfce5ca688ffffa2b96d4fff1f/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: ./patch_bins
sed: bin/ghc: in-place editing only works for regular files
sed: bin/ghc-pkg: in-place editing only works for regular files
sed: bin/ghci: in-place editing only works for regular files
sed: bin/haddock: in-place editing only works for regular files
sed: bin/runghc: in-place editing only works for regular files
sed: bin/runhaskell: in-place editing only works for regular files
ERROR: Analysis of target '//:example' failed; build aborted: Analysis failed
INFO: Elapsed time: 78.180s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 27 targets configured)
FAILED: Build did NOT complete successfully (19 packages loaded, 27 targets configured)
```

**Comment by BinaryHexer** [comment]
Or did I misunderstand something? Should I switch to `rules_haskell` from master instead of `0.13`?

**Comment by BinaryHexer** [comment]
Okay, just tested with the following change, and it works!

WORKSPACE

```diff
- http_archive(
-     name="rules_haskell",
-     strip_prefix="rules_haskell-0.13",
-     urls=["https://github.com/tweag/rules_haskell/archive/v0.13.tar.gz"],
-     sha256 = "b4e2c00da9bc6668fa0404275fecfdb31beb700abdba0e029e74cacc388d94d6",
- )
+ load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
+ git_repository(
+     name="rules_haskell",
+     remote="git@github.com:tweag/rules_haskell.git",
+     commit="915beedca12199fb6240c5c1f48d95f2c686aa4b",
+ )
```

Bazel
3.3.1 -> 3.4.0

**Comment by aherrmann** [comment]
> Or did I misunderstand something? Should I switch to rules_haskell from master instead of 0.13?

Yes, sorry, the rules_haskell version should also be updated.

> Okay, just tested with the following change, and it works!

Thanks for checking and the update. Glad to hear the issue is resolved.
