### ISSUE TITLE
Bazel CI: rules_haskell failing with Bazel 4.2

### ISSUE THREAD

**Issue by meteorcloudy** [tweag/rules_haskell#1650]
https://buildkite.com/bazel/rules-haskell-haskell/builds/964
```
(00:15:43) ERROR: /workdir/tests/binary-with-lib-dynamic/BUILD.bazel:13:16: in _haskell_library rule //tests/binary-with-lib-dynamic:lib:
Traceback (most recent call last):
	File "/workdir/haskell/private/haskell_impl.bzl", line 378, column 25, in haskell_library_impl
		cc = cc_interop_info(
	File "/workdir/haskell/cc.bzl", line 86, column 57, in cc_interop_info
		feature_configuration = cc_common.configure_features(
Error in configure_features: in call to configure_features(), parameter 'cc_toolchain' got value of type 'ToolchainInfo', want 'CcToolchainInfo'
```

**Comment by meteorcloudy** [comment]
@aherrmann
