### ISSUE TITLE
Transitive C dependencies are not linked

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#170]
https://github.com/iphydf/repro170 (output: https://travis-ci.org/iphydf/repro170)

Removing the intermediate `cbits-indirect` fixes it. Adding an indirection through `cbits-indirect` such that e.g. `get_thing` is called from within `cbits-indirect` and `MyModule` only calls that indirection function fixes the linker (ld) error, but replaces it with a dynamic linker (ld.so) error.

```python
load("@io_tweag_rules_haskell//haskell:haskell.bzl", "haskell_binary", "haskell_library")

cc_library(
    name = "cbits-indirect",
    srcs = ["cbits/impl.c"],
)

cc_library(
    name = "cbits",
    deps = ["cbits-indirect"],
)

haskell_library(
    name = "mypkg",
    srcs = ["src/MyModule.hs"],
    prebuilt_dependencies = ["base"],
    src_strip_prefix = "src",
    deps = [":cbits"],
)

haskell_binary(
    name = "mytest",
    srcs = ["test/Main.hs"],
    prebuilt_dependencies = ["base"],
    src_strip_prefix = "test",
    deps = [":mypkg"],
)
```

**Comment by mrkkrp** [comment]
Interesting. I tried to reproduce it, but it fails even earlier because of `ghc_bindist`, like so:

```
1d101a4780ed:/home/repro170# bazel build //mypkg:mytest
........
ERROR: /root/.cache/bazel/_bazel_root/f7f89727f79020a21b1731d34d7ee137/external/ghc/BUILD:14:26: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/f7f89727f79020a21b1731d34d7ee137/external/ghc/BUILD", line 10
                cc_library(name = "threaded-rts", srcs = glob..."]), <2 more arguments>)
        File "/root/.cache/bazel/_bazel_root/f7f89727f79020a21b1731d34d7ee137/external/ghc/BUILD", line 14, in cc_library
                glob(["lib/ghc-*/include"], exclude_directories = 0)[0]
index out of range (index is 0, but sequence has 0 elements)
ERROR: /home/repro170/BUILD.bazel:3:1: Target '@ghc//:bin' contains an error and its package is in error and referenced by '//:ghc-impl'
ERROR: Analysis of target '//mypkg:mytest' failed; build aborted: Loading failed
INFO: Elapsed time: 79.923s
FAILED: Build did NOT complete successfully (11 packages loaded)
```

Here is the output of `bazel version` for me:

```

```

**Comment by mrkkrp** [comment]
Ah OK, it's simpler, the installation procedure requires `perl`. This is not very good that in the case when perl is missing the steps are silently skipped, this may lead to confusion for the users, maybe the situation could be improved.

**Comment by iphydf** [comment]
I'm using 0.9.0, yes, but I doubt the original bug is related to that. I'll update my repro170 repo to use 0.10.0.

**Comment by iphydf** [comment]
0.10.0, same thing: https://travis-ci.org/iphydf/repro170/jobs/349771058#L640

**Comment by mrkkrp** [comment]
I don't think this is a `rules_haskell` bug. In `:mypkg` you use functions from `cbits-indirect` and so you must specify it as a direct dependency.

It would be different if your `:cbits` target introduced some functions that depend on `get_thing` and `set_thing` and exported those new functions. Then in `:mypkg` you could use them (but not `get_thing` and `set_thing`) and it would work. But in this case you are trying to use functions from library you don't depend on. Even though `:cbits-indirect` it's a transitive dependency, this does not mean we should link every target everything against all transitive dependencies accumulated so far.

cc @facundominguez

**Comment by iphydf** [comment]
Right, well, that also doesn't work, like I said: if you do that, you [move the error to runtime](https://travis-ci.org/iphydf/repro170/jobs/350264760#L641).

Error:
```
symbol lookup error: mypkg/libmypkg_Scbits_libcbits.so: undefined symbol: real_get_thing
```

BUILD:
```python
load("@io_tweag_rules_haskell//haskell:haskell.bzl", "haskell_binary", "haskell_library")

cc_library(
    name = "cbits-indirect",
    srcs = ["cbits/impl.c"],
)

cc_library(
    name = "cbits",
    srcs = ["cbits/intf.c"],
    deps = ["cbits-indirect"],
)

haskell_library(
    name = "mypkg",
    srcs = ["src/MyModule.hs"],
    prebuilt_dependencies = ["base"],
    src_strip_prefix = "src",
    deps = [":cbits"],
)

haskell_binary(
    name = "mytest",
    srcs = ["test/Main.hs"],
    prebuilt_dependencies = ["base"],
    src_strip_prefix = "test",
    deps = [":mypkg"],
)
```

**Comment by mrkkrp** [comment]
For me your updated example from the repo fails at linking of `//mypkg:mytest`. Like so:

```
ERROR: /home/repro170/mypkg/BUILD.bazel:22:1: Linking mytest failed (Exit 1)
bazel-out/k8-fastbuild/bin/mypkg/libmypkg_Scbits_libcbits.so: undefined reference to `real_set_thing'
bazel-out/k8-fastbuild/bin/mypkg/libmypkg_Scbits_libcbits.so: undefined reference to `real_get_thing'
```

Maybe there is some difference in how the linker works, I'm not sure. The problem is that `cbits` cannot find `cbits-indirect`. And the bigger problem is that when we have a C dependency, we know nothing about its transitive dependencies. We basically have a `DefaultInfo` provider in that case, and it does not contain such info. I thought there may be a field with runfiles or something, but there is nothing useful.

`CcSkylarkApiProvider` does not contain info about transitive dependencies and it's not visible to us anyway.

I need to find out what cc rules do in such cases.

**Comment by iphydf** [comment]
Will the new C++ Skylark API fix this?

**Comment by iphydf** [comment]
Everything works except this one. This is the last blocker for me to have toktok-stack fully working with rules_haskell.

**Comment by judah** [comment]
For comparison, the ways that Google's Hazel Bazel rules handle this (https://github.com/google/cabal2bazel) is by accessing `RULE.cc.libs`:
https://github.com/google/cabal2bazel/blob/c208bf179c8e820b0733a4472a5825c4f86e8e60/bzl/providers.bzl#L71
Docs:
https://docs.bazel.build/versions/master/skylark/lib/CcSkylarkApiProvider.html#libs

The last time I looked, it does provide a transitive set of `*.a` files for C deps (but not the `.so` files).

**Comment by guibou** [comment]
@iphydf could you test that #394 fix the issue for you?

**Comment by iphydf** [comment]
@guibou yes, this works great, thanks!

**Comment by facundominguez** [comment]
Closing as it seems resolved.

**Comment by mboes** [comment]
Whoa hold on let's wait until #394 is merged into `master` before closing this one.

**Comment by facundominguez** [comment]
Ha! Sorry about that. I was quite convinced it had been merged. :)

**Comment by iphydf** [comment]
#394 is closed but not merged. Is there any additional information I can provide to help move this forward? Does anyone have some code that I can test?

**Comment by iphydf** [comment]
I can confirm that e77556246ff007a8c432faa663a23ecbe1eb51ec (latest commit as of today) does not work.  35195f2005226b76e65bed31f1dd815810f94634 (the commit from #394) does still work.

**Comment by guibou** [comment]
@iphydf Sorry for the time without answers. I'm putting this issue on the top of my stack of things to do. I'm still don't understand all the implications of #394 and associated changes, but I'm now thinking that a poor quality PR which fixs your bug may be better than no PR at all.

Really, sorry for the delay.

**Comment by guibou** [comment]
A bit of followup on this issue.

I'm now convinced that the PR from #394 was the right think to do. I'll reopen it, fix the "cosmetic" issues listed by @mboes.

However, I initially put this PR on hold because of the regression you detailed in #429, AFAIK, #429 is not a regression and if fixed, the same issue as #170 will appear again. Fixing #429 is more complicated because of limitations of the skylark API, I'll describe the issue more in #429.

So I'll soon reopen the pull request and hope for a quick merge for this issue. Work will continue on #429.

**Comment by Profpatsch** [comment]
This is not completely fixed, the `indirect-link` test fails on darwin, see #551.
