### ISSUE TITLE
rules_haskel CIl failing on buildkite

### ISSUE THREAD

**Issue by c-parsons** [tweag/rules_haskell#1715]
rules_haskell has been failing on CI (Bazel's buildkite) since Mar 3 with *release* Bazel.

Example failure:

https://buildkite.com/bazel/rules-haskell-haskell/builds/1069#98b2df97-1fc7-45ae-baa6-4a3da0b2db14

```
(00:17:49) ERROR: An error occurred during the fetch of repository 'rules_haskell_stack':
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_haskell/haskell/cabal.bzl", line 2335, column 33, in _fetch_stack_impl
  | error = _stack_version_check(repository_ctx, stack_cmd)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_haskell/haskell/cabal.bzl", line 1022, column 41, in _stack_version_check
  | exec_result = repository_ctx.execute([stack_cmd, "--numeric-version"])
  | Error in execute: Argument 0 of execute is neither a path, label, nor string.

```

**Comment by ylecornec** [comment]
Thank you, it seems that PR #1716 fixes this problem.

I ran the build again manually to confirm it: https://buildkite.com/bazel/rules-haskell-haskell/builds/1071.
