### ISSUE TITLE
toolchain detection for stack fails on Apple M1

### ISSUE THREAD

**Issue by phb** [tweag/rules_haskell#1823]
cabal.bzl does not have an entry for arm64: https://github.com/tweag/rules_haskell/blame/576d3cb99d4068556a6a301f15b2fb6257ee22c2/haskell/cabal.bzl#L2328

which results in an error when attempting to build rules_haskell on an Apple M1:
```
fail("Failed to determine CPU architecture:\n{}\n{}".format(result.stdout, result.stderr))
Error in fail: Failed to determine CPU architecture: arm64
```

`uname -m` on an Apple M1 provides `arm64`

I noticed that Stack does not provide a binary distribution for arm64 yet, so it's likely this is a known issue and is just waiting for a new Stack release?

**Comment by avdv** [comment]
Could you try rules_haskell from commit 6984bbbccacf6a83cceb17468c7cc6808b2a37a5 and see how this goes?

**Comment by phb** [comment]
Thanks for the quick fix. It still doesn't quite work and it seems the error message collection code is a tad broken so it's not clear what the actual error was.
```
Repository rule _fetch_stack defined at:
  /private/var/tmp/_bazel/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/cabal.bzl:2381:31: in <toplevel>
INFO: Repository 'rules_haskell_stack' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cea34367981ed6f5629d23d17957920b1a06cc0a00580ba62e960a64087f25fe' for https://downloads.haskell.org/ghcup/unofficial-bindists/stack/2.7.5/stack-2.7.5-osx-aarch64.tar.gz
If the definition of 'rules_haskell_stack' was updated, verify that the hashes were also updated.
DEBUG: /private/var/tmp/_bazel/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/cabal.bzl:2361:10: Stack not found.
DEBUG: /private/var/tmp/_bazel/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/cabal.bzl:2362:10: Downloading Stack 2.7.5 ...
ERROR: An error occurred during the fetch of repository 'rules_haskell_stack':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/cabal.bzl", line 2372, column 22, in _fetch_stack_impl
                error_message.append("A Stack binary for your platform exists,")
Error: 'string' value has no field or method 'append'
ERROR: WORKSPACE:414:15: fetching _fetch_stack rule //external:rules_haskell_stack: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/cabal.bzl", line 2372, column 22, in _fetch_stack_impl
                error_message.append("A Stack binary for your platform exists,")
Error: 'string' value has no field or method 'append'
```

**Comment by tsiq-aaronh** [comment]
I'm interested in this fix, too. Hopefully it's a quick one.

**Comment by avdv** [comment]
I think I fixed a few things again. Please have a look at #1825 and test if it works for you now.

**Comment by tsiq-aaronh** [comment]
Still seeing an error: 

```
INFO: Repository 'rules_haskell_ghc_darwin_arm64' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b1fcab17fe48326d2ff302d70c12bc4cf4d570dfbbce68ab57c719cfec882b05' for https://downloads.haskell.org/~ghc/9.0.2/ghc-9.0.2-aarch64-apple-darwin.tar.xz
If the definition of 'rules_haskell_ghc_darwin_arm64' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'rules_haskell_ghc_darwin_arm64':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/ghc_bindist.bzl", line 112, column 29, in _ghc_bindist_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell_ghc_darwin_arm64/bindist_unpacked/temp2166312922655016515/ghc-9.0.2-aarch64-apple-darwin.tar.xz to /private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell_ghc_darwin_arm64/bindist_unpacked/temp2166312922655016515: Prefix "ghc-9.0.2" was given, but not found in the archive. Here are possible prefixes for this archive: "ghc-9.0.2-aarch64-apple-darwin".
```

**Comment by avdv** [comment]
@tsiq-aaronh Oh yes, that is expected since you will need the changes from #1808

**Comment by tsiq-aaronh** [comment]
Makes sense, this is what I get now:

```ERROR: /private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/stackage/BUILD.bazel:867:26: in haskell_toolchain_library rule @stackage//:text: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/rules_haskell/haskell/private/haskell_impl.bzl", line 798, column 13, in haskell_toolchain_library_impl
                fail(
Error in fail: 
text is not a toolchain library.
Check that it ships with your version of GHC.
The following toolchain libraries are available:
{}
            
ERROR: /private/var/tmp/_bazel_aaron/e6d9b6ac2f68e03f41d5722309122fa0/external/stackage/BUILD.bazel:867:26: Analysis of target '@stackage//:text' failed
ERROR: Analysis of target '//package:package' failed; build aborted: 
INFO: Elapsed time: 58.874s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (614 packages loaded, 34950 targets configured)```

**Comment by avdv** [comment]
@tsiq-aaronh  This is probably https://github.com/tweag/rules_haskell/issues/1809 what you're seeing here.

**Comment by tsiq-aaronh** [comment]
Agreed 😞 Will watch for an update on that one.
