### ISSUE TITLE
GHC bindist version 9.4.x fails on Windows

### ISSUE THREAD

**Issue by avdv** [tweag/rules_haskell#1892]
**Describe the bug**
Trying to run the example on Windows using the run-start-script.sh fails with a linker error:
```
    $ bazel run //:example
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //:example (1 packages loaded, 0 targets configured)
Analyzing: target //:example (2 packages loaded, 0 targets configured)
Analyzing: target //:example (2 packages loaded, 0 targets configured)
Analyzing: target //:example (8 packages loaded, 9 targets configured)
Analyzing: target //:example (8 packages loaded, 9 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
Analyzing: target //:example (43 packages loaded, 138 targets configured)
WARNING: C:/users/runneradmin/_bazel_runneradmin/z5des2pa/external/zlib.dev/BUILD.bazel:3:11: in linkstatic attribute of cc_library rule @zlib.dev//:zlib: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
INFO: Analyzed target //:example (61 packages loaded, 15547 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[49 / 53] PythonZipper external/rules_haskell/haskell/runghc.zip [for host]; 9s local
[50 / 53] HaskellCabalLibrary @stackage//:zlib; 45s local
ERROR: C:/users/runneradmin/_bazel_runneradmin/z5des2pa/external/stackage/BUILD.bazel:12:22: HaskellCabalLibrary @stackage//:zlib failed: (Exit 1): cabal_wrapper.exe failed: error executing command 
  cd /d C:/users/runneradmin/_bazel_runneradmin/z5des2pa/execroot/YOUR_PROJECT_NAME_HERE
  SET CC_WRAPPER_CC_PATH=external/rules_haskell_ghc_windows_amd64/mingw/bin/clang
    SET CC_WRAPPER_CPU=x64_windows
    SET CC_WRAPPER_PLATFORM=windows
    SET LANG=C.UTF-8
    SET PATH=C:/Program Files/Git/usr/bin
    SET RULES_HASKELL_DOCDIR_PATH=external/rules_haskell_ghc_windows_amd64/doc/html/libraries/base-4.17.1.0
    SET RULES_HASKELL_GHC_PATH=external/rules_haskell_ghc_windows_amd64/bin/ghc-9.4.5.exe
    SET RULES_HASKELL_GHC_PKG_PATH=external/rules_haskell_ghc_windows_amd64/bin/ghc-pkg-9.4.5.exe
    SET RULES_HASKELL_LIBDIR_PATH=external/rules_haskell_ghc_windows_amd64/lib
  bazel-out\host\bin\external\rules_haskell\haskell\cabal_wrapper.exe bazel-out/x64_windows-fastbuild/bin/external/stackage/zlib_cabal_wrapper_args.json
# Configuration: 67fb4b74e9719aa164e4952fab4f7738bc7a25d3b56f82ede09f39745612c250
# Execution platform: @local_config_platform//:host
lld: error: unknown argument: -r
lld: error: unknown argument: -r
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<no location info>: error:
    `clang.exe' failed in phase `Merge objects'. (Exit code: 1)
Traceback (most recent call last):
  File "\\?\C:\Users\RUNNER~1\AppData\Local\Temp\zlib-0.6.3.0\tmp\Bazel.runfiles_xy1_m96r\runfiles\rules_haskell\haskell\runghc.py", line 9, in <module>
    subprocess.run([r.Rlocation("rules_haskell_ghc_windows_amd64/bin/runghc-9.4.5.exe")] + sys.argv[1:], check=True)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:/users/runneradmin/_bazel_runneradmin/z5des2pa/external/rules_haskell_ghc_windows_amd64/bin/runghc-9.4.5.exe', 'C:\\users\\runneradmin\\_bazel_runneradmin\\z5des2pa\\execroot\\YOUR_PROJECT_NAME_HERE\\bazel-out/x64_windows-fastbuild/bin/external/stackage/zlib-0.6.3.0/Setup.hs', 'build', '--verbose=0', '--builddir=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\zlib-0.6.3.0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_u6a008rv\runfiles\rules_haskell\haskell\private\cabal_wrapper.py", line 345, in <module>
    run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  File "\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_u6a008rv\runfiles\rules_haskell\haskell\private\cabal_wrapper.py", line 69, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\users\\runneradmin\\_bazel_runneradmin\\z5des2pa\\execroot\\YOUR_PROJECT_NAME_HERE\\bazel-out\\host\\bin\\external\\rules_haskell\\haskell\\runghc.exe', 'C:\\users\\runneradmin\\_bazel_runneradmin\\z5des2pa\\execroot\\YOUR_PROJECT_NAME_HERE\\bazel-out/x64_windows-fastbuild/bin/external/stackage/zlib-0.6.3.0/Setup.hs', 'build', '--verbose=0', '--builddir=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\zlib-0.6.3.0']' returned non-zero exit status 1.
Target //:example failed to build
INFO: Elapsed time: 632.557s, Critical Path: 104.15s
INFO: 51 processes: 32 internal, 19 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Error: Process completed with exit code 1.
```
See https://github.com/tweag/rules_haskell/actions/runs/4881535298/jobs/8710565531#step:7:92

**To Reproduce**
On Windows, run
```
export GHC_VERSION=9.4.5
tests/run-start-script.sh --use-bindists
```

**Expected behavior**
It should not fail with a linker error.

Note, GHC version 9.6.1 which uses the exact same llvm toolchain (AFAICS) can run the example successfully.

This is related to the Cabal version: https://github.com/haskell/cabal/issues/8780

**Environment**
 - OS name + version: Windows
 - Bazel version: 5.2.0
 - Version of the rules: 

**Additional context**

**Comment by avdv** [comment]
This seems to be caused by this change: https://gitlab.haskell.org/ghc/ghc/-/commit/694d39f0391c58cd926887e274c227e99099a900

i.e. if we pass in a program via the `-pgmlm` option (which we do for GHC >= 9), GHC is assuming the linker supports object merging via the `-r` flag, which the lld-ld linker does not understand.

GHC >= 9.6 works again, since it requires another predicate to be falsy ([wether `ar` supports `-L`](https://gitlab.haskell.org/ghc/ghc/-/commit/112e4f9c9c299b460e37a60d8f8d8693aa6ab06a))
