### ISSUE TITLE
Hashable fails to build on macos bindist

### ISSUE THREAD

**Issue by jmorag** [tweag/rules_haskell#2042]
**Describe the bug**
Cannot build hashable using a stackage snapshot with the bindist toolchain on macos aarch64.

**To Reproduce**
WORKSPACE file
```bazel
workspace(name = "bazel-hashable")

# Load the repository rule to download an http archive.
load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive"
)

# Download rules_haskell and make it accessible as "@rules_haskell".
http_archive(
    name = "rules_haskell",
    sha256 = "298f6f0db23391274b4eca215daa01797d05699469048ef94540d5829b466377",
    strip_prefix = "rules_haskell-0.17",
    url = "https://github.com/tweag/rules_haskell/archive/refs/tags/v0.17.tar.gz",
)

load(
    "@rules_haskell//haskell:repositories.bzl",
    "rules_haskell_dependencies",
)

# Setup all Bazel dependencies required by rules_haskell.
rules_haskell_dependencies()

load(
    "@rules_haskell//haskell:toolchain.bzl",
    "rules_haskell_toolchains",
)

load(
    "@rules_haskell//haskell:cabal.bzl",
    "stack_snapshot"
)

stack_snapshot(
    name = "stackage",
    packages = ["hashable"],
    snapshot = "lts-20.3",
)

# Download a GHC binary distribution from haskell.org and register it as a toolchain.
rules_haskell_toolchains(
    version = "9.2.5",
)
```

Example.hs
```haskell
module Main where

import Data.Hashable
import System.Environment (getArgs)

main = do
  args <- getArgs
  print (hash args)
```

Build.bazel
```bazel
package(default_visibility = ["//visibility:public"])

load(
    "@rules_haskell//haskell:defs.bzl",
    "haskell_toolchain_library",
    "haskell_library",
    "haskell_binary",
)

haskell_toolchain_library(name = "base")

haskell_binary(
    name = "example",
    srcs = [":Example.hs"],
    deps = [":base", "@stackage//:hashable"],
)
```

Running `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel build //:example` produces the following output. I don't think the warnings about FNV hash matter but I'm not sure.

```
NFO: Analyzed target //:example (60 packages loaded, 9984 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/external/stackage/BUILD.bazel:24:22: HaskellCabalLibrary @stackage//:hashable failed: (Exit 1): cabal_wrapper failed: error executing command (from target @stackage//:hashable) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/cabal_wrapper bazel-out/darwin_arm64-fastbuild/bin/external/stackage/hashable_cabal_wrapper_args.json

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]

/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-fastbuild/bin/external/stackage/hashable-1.4.1.0/hashable-1.4.1.0/tmp/ghc92933_0/ghc_14.c:11:155: error:
     warning: passing 'char *' to parameter of type 'const unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
   |
11 | HsWord64 ghczuwrapperZC1ZChashablezm1zi4zi1zi0ZCDataziHashableziLowLevelZChashablezufnvzuhash(char* a1, HsInt64 a2, HsInt64 a3) {return hashable_fnv_hash(a1, a2, a3);}
   |                                                                                                                                                           ^
HsWord64 ghczuwrapperZC1ZChashablezm1zi4zi1zi0ZCDataziHashableziLowLevelZChashablezufnvzuhash(char* a1, HsInt64 a2, HsInt64 a3) {return hashable_fnv_hash(a1, a2, a3);}
                                                                                                                                                          ^~

include/HsHashable.h:19:53: error:
     note: passing argument to parameter 'str' here
   |
19 | FNV_UNSIGNED hashable_fnv_hash(const unsigned char* str, FNV_SIGNED len, FNV_UNSIGNED salt);
   |                                                     ^
FNV_UNSIGNED hashable_fnv_hash(const unsigned char* str, FNV_SIGNED len, FNV_UNSIGNED salt);
                                                    ^
1 warning generated.
ld: warning: -arch not specified
ld: warning: ignoring file /private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-fastbuild/bin/external/stackage/hashable-1.4.1.0/hashable-1.4.1.0/tmp/ghc92933_0/ghc_19.ldscript, building for -unknown but attempting to link with file built for unknown-unsupported file format ( 0x49 0x4E 0x50 0x55 0x54 0x28 0x22 0x2F 0x70 0x72 0x69 0x76 0x61 0x74 0x65 0x2F )
0  0x102aa40c0  __assert_rtn + 140
1  0x102ab09b4  ld::passes::objc::fixClassAliases(ld::Internal const&, ld::Atom const*, unsigned long long&) (.cold.1) + 0
2  0x102a3f508  bool ld::passes::objc::scanCategories<arm64e>(ld::Internal&) + 0
3  0x1028ed93c  main + 656
A linker snapshot was created at:
	/tmp/LowLevel.o-2023-11-14-104828.ld-snapshot
ld: Assertion failed: (0 && "unknown objc arch"), function doPass, file objc.cpp, line 2732.
`ld' failed in phase `Merge objects'. (Exit code: 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/runghc.runfiles/rules_haskell/haskell/runghc.py", line 9, in <module>
    subprocess.run([r.Rlocation("rules_haskell_ghc_darwin_arm64/bin/runghc")] + sys.argv[1:], check=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/runghc.runfiles/rules_haskell_ghc_darwin_arm64/bin/runghc', '/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/external/stackage/hashable-1.4.1.0/Setup.hs', 'build', '--verbose=0', '--builddir=/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-fastbuild/bin/external/stackage/hashable-1.4.1.0/hashable-1.4.1.0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/private/cabal_wrapper.py", line 345, in <module>
    run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  File "/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/private/cabal_wrapper.py", line 69, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_haskell/haskell/runghc', '/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/external/stackage/hashable-1.4.1.0/Setup.hs', 'build', '--verbose=0', '--builddir=/private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/sandbox/darwin-sandbox/1/execroot/bazel-hashable/bazel-out/darwin_arm64-fastbuild/bin/external/stackage/hashable-1.4.1.0/hashable-1.4.1.0']' returned non-zero exit status 1.
Target //:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 53.613s, Critical Path: 10.84s
INFO: 7 processes: 7 internal.
FAILED: Build did NOT complete successfully
```

**Expected behavior**
Expected a successful build. Using this minimal cabal file with `cabal build` works fine.
```
cabal-version: 3.0
name:          bazel-hashable
version:       0.0.0.1

executable example
  main-is:       Example.hs
  default-language: Haskell2010
  build-depends:
    , base
    , hashable
```

**Environment**
 - OS name + version: MacOS Ventura 13.1 (aarch64)
 - Bazel version: 6.3.2
 - Version of the rules: 0.17

**Additional context**

**Comment by avdv** [comment]
Hi.

Thank you for reporting the problem and the minimal example!

I tried running on:
```console
$ sw_vers                                                                                                                                               
ProductName:	macOS
ProductVersion:	12.7
BuildVersion:	21G816
$ bazel version                                                                                                                       ~/foof
Bazelisk version: v1.18.0
Build label: 6.3.2
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Aug 8 15:51:44 2023 (1691509904)
Build timestamp: 1691509904
Build timestamp as int: 1691509904
```
and it was successful. So it's something in your environment that's different. (you could set up a nixpkgs based toolchain instead, to not rely on the tools available on your machine)

What's the output of `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel query @local_config_cc//:local --output build`?

I just found this [change](https://github.com/radareorg/radare2/pull/17879/files) which fixed a similar [problem](https://github.com/radareorg/radare2/issues/17870). This seems to suggest we need to pass `-arch ... ` to the linker for newer Xcode, IIUC.

**Comment by jmorag** [comment]
Thanks for the quick response! Here's what I'm running on
```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
$ bazel version
Bazelisk version: development
Build label: 6.3.2
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Aug 8 15:51:44 2023 (1691509904)
Build timestamp: 1691509904
Build timestamp as int: 1691509904
```
and here's the output for the query
```
$ BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel query @local_config_cc//:local --output build                       ░▒▓ ✔ 
# /private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/external/local_config_cc/BUILD:74:20
cc_toolchain_config(
  name = "local",
  cpu = "darwin_arm64",
  compiler = "clang",
  toolchain_identifier = "local",
  host_system_name = "local",
  target_system_name = "local",
  target_libc = "macosx",
  abi_version = "local",
  abi_libc_version = "local",
  cxx_builtin_include_directories = ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/share", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"],
  tool_paths = {"ar": "/usr/bin/libtool", "ld": "/usr/bin/ld", "llvm-cov": "/opt/homebrew/opt/llvm@13/bin/llvm-cov", "llvm-profdata": "/opt/homebrew/opt/llvm@13/bin/llvm-profdata", "cpp": "/usr/bin/cpp", "gcc": "cc_wrapper.sh", "dwp": "/usr/bin/dwp", "gcov": "/usr/bin/gcov", "nm": "/usr/bin/nm", "objcopy": "/usr/bin/objcopy", "objdump": "/usr/bin/objdump", "strip": "/usr/bin/strip"},
  compile_flags = ["-fstack-protector", "-Wall", "-Wthread-safety", "-Wself-assign", "-Wunused-but-set-parameter", "-Wno-free-nonheap-object", "-fcolor-diagnostics", "-fno-omit-frame-pointer"],
  dbg_compile_flags = ["-g"],
  opt_compile_flags = ["-g0", "-O2", "-D_FORTIFY_SOURCE=1", "-DNDEBUG", "-ffunction-sections", "-fdata-sections"],
  cxx_flags = ["-std=c++0x"],
  link_flags = ["-undefined", "dynamic_lookup", "-headerpad_max_install_names"],
  link_libs = ["-lc++", "-lm"],
  opt_link_flags = [],
  unfiltered_compile_flags = ["-no-canonical-prefixes", "-Wno-builtin-macro-redefined", "-D__DATE__=\"redacted\"", "-D__TIMESTAMP__=\"redacted\"", "-D__TIME__=\"redacted\""],
  coverage_compile_flags = ["-fprofile-instr-generate", "-fcoverage-mapping"],
  coverage_link_flags = ["-fprofile-instr-generate"],
  supports_start_end_lib = False,
)
# Rule local instantiated at (most recent call last):
#   /private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/external/local_config_cc/BUILD:74:20 in <toplevel>
# Rule cc_toolchain_config defined at (most recent call last):
#   /private/var/tmp/_bazel_josephmorag/ce20fc759eaad33cfae6b6c8d04096a5/external/local_config_cc/cc_toolchain_config.bzl:1407:27 in <toplevel>

Loading: 0 packages loaded
```

**Comment by jmorag** [comment]
Looking at this output, I thought it might be an issue with having llvm@13 in my path, but I removed it, tried again, and got the same linker error, so I don't think that's the issue.

**Comment by avdv** [comment]
> Looking at this output, I thought it might be an issue with having llvm@13 in my path, but I removed it, tried again, and got the same linker error, so I don't think that's the issue.

Bazel might not have picked up that change in your environment. Run `bazel clean` and try again. Also look at the output of the query again, did it change?

**Comment by avdv** [comment]
Unfortunately, there is no easy way to pass additional arguments to the generated `haskell_cabal_library` calls.

But you could create your own linker wrapper script:
```bash
#!/usr/bin/env bash

exec /usr/bin/ld -arch arm64 "$@"
```
Put this into `bin/ld` and `chmod +x`.

Then, add the bin folder to PATH and make Bazel rebuild the cc toolchain repository:
```console
$ ls -lh bin
ls -lh bin
total 8
-rwxr-xr-x  1 claudio  staff    58B Nov 15 10:29 ld
$ PATH=$(pwd)/bin:$PATH
$ BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 ./bazelisk-darwin-arm64 build ...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
$ BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 ./bazelisk-darwin-arm64 build ...
...
```

**Comment by avdv** [comment]
Also, maybe just try the latest Bazel version.

**Comment by jmorag** [comment]
Updating rules_cc works! Thanks for the suggestion. I wouldn't have thought to try that. Is there a way we can update rules_haskell to load latest rules_cc automatically or should we just document this in the readme alongside other common macos issues.

**Comment by avdv** [comment]
> Is there a way we can update rules_haskell to load latest rules_cc automatically or should we just document this in the readme alongside other common macos issues.

We already have set up renovate to keep dependencies up to date, see https://github.com/tweag/rules_haskell/pull/2007/commits/dadc472c9b5bd0d6377403382e045f05b57e4213

Of course, we need to publish a release before users benefit automatically.

**Comment by avdv** [comment]
This should now work out-of-the-box in rules_haskell 0.18.

But note, in the future we will follow the recommended practice of only upgrading dependencies of the root module(s) if necessary -- so dependencies truly reflect the *minimal* required versions of our module. We will ensure compatibility with more recent versions by keeping dependencies of our test module up-to-date.

This way we don't force upgrades to users of our module, which could pose a problem if you cannot update other modules for some reason. But if you need a newer version of some module you may do so and add a dependency on that module to your `MODULE.bazel` file.
