### ISSUE TITLE
Unstuck at the first build in the tutorial

### ISSUE THREAD

**Issue by philderbeast** [tweag/rules_haskell#409]
I started on the tutorial and came unstuck at the first build when instructed to;

    bazel build //lib:booleans

https://github.com/tweag/rules_haskell/blame/master/docs/haskell.rst#L108

Here's the failure;

```
> bazel build //lib:booleans
ERROR: Skipping '//lib:booleans': no such package 'lib': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'lib': BUILD file not found on package path
INFO: Elapsed time: 0.064s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

This looks like it worked but `found 0 targets`;

```
> bazel build //tutorial:lib:booleans
INFO: Analysed 0 targets (2 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 5.997s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
```

This also worked on `0 targets` so counts as a failure building the tutorial lib;

```
> bazel build /tutorial/lib:booleans
INFO: Analysed 0 targets (0 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 0.112s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

I had tried from the `/tutorial` directory too;

```
tutorial> bazel build //lib:booleans
..........
these paths will be fetched (255.59 MiB download, 1929.46 MiB unpacked):
/nix/store/01ac3w0c54fl4mfy55m6f9adkmmf3z31-binutils-2.28.1
...
/nix/store/qsfhacppm13v295jmjn8fv4pxjdy0wxd-ghc-8.2.2
ERROR: /.../tutorial/lib/BUILD:1:1: in haskell_library rule //lib:booleans:
Traceback (most recent call last):
	File "/.../tutorial/lib/BUILD", line 1
		haskell_library(name = 'booleans')
	File "/private/var/tmp/_bazel_pdejoux/f22794170b7ca640411f5c01bfb84c9e/external/io_tweag_rules_haskell/haskell/private/haskell_impl.bzl", line 164, in haskell_library_impl
		cc_interop_info(ctx)
	File "/private/var/tmp/_bazel_pdejoux/f22794170b7ca640411f5c01bfb84c9e/external/io_tweag_rules_haskell/haskell/cc.bzl", line 91, in cc_interop_info
		CcInteropInfo(hdrs = hdrs.to_list(), cpp_flags =..., <3 more arguments>)
	File "/private/var/tmp/_bazel_pdejoux/f22794170b7ca640411f5c01bfb84c9e/external/io_tweag_rules_haskell/haskell/cc.bzl", line 95, in CcInteropInfo
		cc_toolchain.compiler_options()
struct has no method 'compiler_options'
ERROR: Analysis of target '//lib:booleans' failed; build aborted: Analysis of target '//lib:booleans' failed; build aborted
INFO: Elapsed time: 60.295s
FAILED: Build did NOT complete successfully (10 packages loaded)
```

**Comment by mboes** [comment]
Looks like your version of Bazel isn't recent enough. What does the following say?

```
$ bazel version
```

The `start` script referenced in the README checks for recent enough Bazel.

**Comment by philderbeast** [comment]
```
> bazel version
Build label: 0.11.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun May 1 04:04:22 +50118 (1519414517062)
Build timestamp: 1519414517062
Build timestamp as int: 1519414517062
```

I installed it today using the [recommended mac instructions](https://docs.bazel.build/versions/master/install-os-x.html), using the binary installer. I did notice that [release 0.16.1](https://github.com/bazelbuild/bazel/releases/tag/0.16.1) was made 8 days ago but the build time of the installer was May 1 as shown in the version dump.

**Comment by philderbeast** [comment]
I'll try an alternate means of installation to get an up to date bazel version.

**Comment by philderbeast** [comment]
I uninstalled the brew install of bazel and installed bazel using the recommended installation script;

```
> brew uninstall bazel
> chmod +x bazel-0.16.1-installer-darwin-x86_64.sh
> ./bazel-0.16.1-installer-darwin-x86_64.sh --user
> bazel version
WARNING: --batch mode is deprecated.
Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770
```

If I follow the tutorial and change into the `/tutorial` folder then the build completes;

```
tutorial> bazel build //lib:booleans
Starting local Bazel server and connecting to it...
/nix/store/qsfhacppm13v295jmjn8fv4pxjdy0wxd-ghc-8.2.2
INFO: Analysed target //lib:booleans (11 packages loaded).
INFO: Found 1 target...
Target //lib:booleans up-to-date:
  bazel-bin/lib/libZSbooleans-1.0.0/libZSbooleans-1.0.0.conf
  bazel-bin/lib/libZSbooleans-1.0.0/package.cache
INFO: Elapsed time: 20.785s, Critical Path: 2.25s
INFO: 10 processes: 10 darwin-sandbox.
INFO: Build completed successfully, 12 total actions
```

**Comment by mboes** [comment]
OK. And I updated the guide to mention changing to the tutorial folder.

**Comment by philderbeast** [comment]
I saw that! Thanks.
