### ISSUE TITLE
Support for Bazel v0.22

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#696]
current `master` fails with bazel 0.22 with:

```
Traceback (most recent call last):
	File "/home/guillaume/tweag/rules_haskell/tests/c-compiles/BUILD", line 9
		haskell_library(name = 'hs-lib')
	File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/external/io_tweag_rules_haskell/haskell/private/haskell_impl.bzl", line 197, in haskell_library_impl
		gather_dep_info(ctx)
	File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/external/io_tweag_rules_haskell/haskell/private/dependencies.bzl", line 155, in gather_dep_info
		_HaskellCcInfo_from_CcInfo(ctx, dep[CcInfo])
	File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/external/io_tweag_rules_haskell/haskell/private/dependencies.bzl", line 23, in _HaskellCcInfo_from_CcInfo
		cc_info.linking_context.static_mode_params_for_executable
object of type 'CcLinkingContext' has no field 'static_mode_params_for_executable'
```

`cc_info.linking_context.stati_mode_params_for_executable` is not provided anymore. I'm not able to find any reference to this change online.

I've found the list of libraries using:

```
    libs = cc_info.linking_context.libraries_to_link
    
    static_linking = [lib.static_library for lib in libs if lib.static_library]
    dynamic_linking = [lib.dynamic_library for lib in libs if lib.dynamic_library]
```

Libraries are provided as `File`, so they don't have the `artifact` and `original_artifact` previously used. Note that `libs` also contains a `pic_static_library` field which may be of use to fix #429.

**Comment by guibou** [comment]
@aherrmann You introduces theses changes recently.

**Comment by guibou** [comment]
See code exemple in b804527eae978b5c30276e6e43272d45a4506c86
