### ISSUE TITLE
Protobuf failure when proto_library uses strip_import_prefix

### ISSUE THREAD

**Issue by andyscott** [tweag/rules_haskell#717]
I'm hitting the following error whenever I attempt to have a `haskell_proto_library` depend on `proto_library`target that uses `strip_import_prefix`:

```
ERROR: /Users/andyscott/personal/git/andyscott/raziel/thirdparty/bazel/src/main/protobuf/BUILD:10:1: in @io_tweag_rules_haskell//haskell:protobuf.bzl%_haskell_proto_aspect aspect on proto_library rule //thirdparty/bazel/src/main/protobuf:option_filters_proto:
Traceback (most recent call last):
	File "/Users/andyscott/personal/git/andyscott/raziel/thirdparty/bazel/src/main/protobuf/BUILD", line 10
		@io_tweag_rules_haskell//haskell:protobuf.bzl%_haskell_proto_aspect(...)
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 107, in _haskell_proto_aspect_impl
		hs_files.append(ctx.actions.declare_file(_proto_...))))
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 107, in hs_files.append
		ctx.actions.declare_file(_proto_lens_output_file(_proto_p...)))
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 108, in ctx.actions.declare_file
		_proto_lens_output_file(_proto_path(src))
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 45, in _proto_lens_output_file
		"/".join([_camel_case(p) for p in path.sp...")])
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 45, in "/".join
		_camel_case(p)
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 34, in _camel_case
		"".join([_capitalize_first_letter(c2) fo...")])
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 35, in "".join
		_capitalize_first_letter(c2)
	File "/private/var/tmp/_bazel_andyscott/854b10ebc332f17901c677433d2de2aa/external/io_tweag_rules_haskell/haskell/protobuf.bzl", line 27, in _capitalize_first_letter
		c[0]
```

For now I'm just avoiding `strip_import_prefix` and modifying my .proto sources.

**Comment by Profpatsch** [comment]
I can’t see an actual error message in that stack trace. :sos:

@andyscott would it be possible to prepare a minimal repro for this issue?

@guibou since this is about aspects, maybe you have an idea.

**Comment by andyscott** [comment]
There are two problems-- one is a simple bug fix with the camel case logic. The second one is a feature augmentation for the proto rules :).

I went ahead and opened a PR with a preliminary fix.
