### ISSUE TITLE
Bazel out of memory

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#966]
**Describe the bug**

I observe java out of memory error many times per day. That's really difficult to bisect (to know if it comes from rules_haskell or bazel).

```
INFO: Invocation ID: ec8efc3b-3fd8-44e4-a2bd-098fe37a8d99
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at com.google.devtools.build.lib.syntax.ListComprehension$ListOutputCollector.evaluateAndCollect(ListComprehension.java:96)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:310)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.doEval(AbstractComprehension.java:278)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.BinaryOperatorExpression.doEval(BinaryOperatorExpression.java:252)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:837)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:901)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:70)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:191)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:128)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)

INFO: Elapsed time: 58.195s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 1438 t\
argets configured)
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at com.google.devtools.build.lib.syntax.ListComprehension$ListOutputCollector.evaluateAndCollect(ListComprehension.java:96)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:310)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.doEval(AbstractComprehension.java:278)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.BinaryOperatorExpression.doEval(BinaryOperatorExpression.java:252)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:837)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:901)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:70)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:191)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:128)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at com.google.devtools.build.lib.syntax.ListComprehension$ListOutputCollector.evaluateAndCollect(ListComprehension.java:96)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:310)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.access$000(AbstractComprehension.java:43)
	at com.google.devtools.build.lib.syntax.AbstractComprehension$ForClause.eval(AbstractComprehension.java:123)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.evalStep(AbstractComprehension.java:312)
	at com.google.devtools.build.lib.syntax.AbstractComprehension.doEval(AbstractComprehension.java:278)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.BinaryOperatorExpression.doEval(BinaryOperatorExpression.java:252)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:837)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:901)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:70)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:191)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:128)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
Java heap space
FAILED: Build did NOT complete successfully (19 packages loaded, 1438 t\
argets configured
```

**Comment by guibou** [comment]
Note:

Memory profiling:

```
Warning: this information is intended for consumption by developers
only, and may change at any time.  Script against it at your own risk!

RULE                                COUNT     ACTIONS          BYTES         EACH  
sh_test                             1,318       7,908      3,670,104        2,784  
haskell_repl                          264       5,333      1,835,224        6,951  
haskell_import                        251         251      1,048,544        4,177  
genrule                               201         201        524,240        2,608  
clang_tidy_test                       186       1,116        524,312        2,818  
haskell_test                          102      13,108      1,572,920       15,420  
haskell_library                        99      15,488      2,883,912       29,130  
py_binary                              81         405              0            0  
py_test                                77         462        262,064        3,403  
filegroup                              76          76        786,592       10,349  
cc_library                             64         541              0            0  
cc_binary                              49         511        786,544       16,051  
toolchain                              47           0              0            0  
haskell_binary                         30       5,710        786,672       26,222  
constraint_value                       27           0              0            0  
config_setting                         27           0              0            0  
py_library                             27           0              0            0  
cc_toolchain                            8           0              0            0  
toolchain_type                          8           0              0            0  
stm32_toolchain_config                  4           0              0            0  
sh_binary                               4          20              0            0  
cc_test                                 4          45              0            0  
sh_library                              3           0              0            0  
constraint_setting                      3           0              0            0  
py_runtime                              3           0              0            0  
c2hs_library                            2           2              0            0  
java_runtime                            2           2              0            0  
platform                                2           0              0            0  
java_import                             2           2              0            0  
java_toolchain                          2           0              0            0  
java_runtime_alias                      1           0              0            0  
x86_64_clang_toolchain_config           1           0              0            0  
_haskell_toolchain                      1           2              0            0  
_c2hs_toolchain                         1           0              0            0  
aarch64_toolchain_config                1           0              0            0  
expand_pyversion_template               1           2              0            0  
java_binary                             1          10              0            0  
cc_toolchain_suite                      1           0              0            0  
extra_action                            1           0              0            0  
java_toolchain_alias                    1           0              0            0  
cc_toolchain_config                     1           0              0            0  
haskell_doc                             1         161              0            0  
x86_64_gcc_toolchain_config             1           0              0            0  
py_runtime_pair                         1           0              0            0  
bootclasspath                           1           2              0            0  
action_listener                         1           0              0            0  
java_host_runtime_alias                 1           0              0            0  

ASPECT                               COUNT     ACTIONS          BYTES         EACH  
haskell_repl_aspect                    696           0        524,256          753  
haskell_doc_aspect                     336         127              0            0  
compilation_database_aspect             93          93        524,504        5,639 
```

Nothing really alarming.

**Comment by guibou** [comment]
Skylark profile:

```
Main binary filename not available.
Type: memory
Time: Jun 24, 2019 at 9:17pm (CEST)
Showing nodes accounting for 11009.24kB, 100% of 11009.24kB total
      flat  flat%   sum%        cum   cum%
 3584.41kB 32.56% 32.56%  3584.41kB 32.56%  ln /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/path_utils.bzl:526
 1024.16kB  9.30% 41.86%  1024.16kB  9.30%  symlink_dynamic_library /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/path_utils.bzl:162
  768.19kB  6.98% 48.84%   768.19kB  6.98%  sh_test <native>:-1
  768.16kB  6.98% 55.82%   768.16kB  6.98%  filegroup <native>:-1
  512.16kB  4.65% 60.47%   512.16kB  4.65%  pkg_info_to_compile_flags /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/packages.bzl:41
  512.02kB  4.65% 65.12%   512.02kB  4.65%  rule <native>:-1
  256.12kB  2.33% 67.45%   256.12kB  2.33%  _compilation_database_aspect_impl /home/guillaume/kitty/heavisoft/tools/kitty_bazel/clang_tools.bzl:142
  256.09kB  2.33% 69.77%   256.09kB  2.33%  HaskellLibraryInfo /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/providers.bzl:35
  256.09kB  2.33% 72.10%   256.09kB  2.33%  _sources /home/guillaume/kitty/heavisoft/tools/kitty_bazel/clang_tools.bzl:56
  256.07kB  2.33% 74.42%   256.07kB  2.33%  _empty /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/set.bzl:11
  256.04kB  2.33% 76.75%   256.04kB  2.33%  bind <native>:-1
  256.01kB  2.33% 79.07%   256.01kB  2.33%  genrule <native>:-1
  255.99kB  2.33% 81.40%   255.99kB  2.33%  HaskellReplCollectInfo /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/repl.bzl:48
  255.99kB  2.33% 83.73%   255.99kB  2.33%  _run_ghc /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/toolchain.bzl:52
  255.99kB  2.33% 86.05%   255.99kB  2.33%  list_exposed_modules /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/actions/compile.bzl:527
  255.98kB  2.33% 88.38%   255.98kB  2.33%  haskell_import_impl /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/haskell_impl.bzl:744
  255.98kB  2.33% 90.70%   255.98kB  2.33%  HaskellReplLoadInfo /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/repl.bzl:23
  255.95kB  2.32% 93.03%   255.95kB  2.32%  _run_ghc /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/toolchain.bzl:96
  255.95kB  2.32% 95.35%   255.95kB  2.32%  cc_binary <native>:-1
  255.95kB  2.32% 97.68%   255.95kB  2.32%  HaskellImportHack /home/guillaume/.cache/bazel/_bazel_guillaume/9923957c70cd7b59bec21e32af97c8be/external/io_tweag_rules_haskell/haskell/private/haskell_impl.bzl:609
```

More interesting ;)

**Comment by guibou** [comment]
Apparently a huge amount of the allocated memory is done during the symlink phase. Perhaps #960 may solve this issue a bit.

However I'm suprised because the OOM always arise in a `Array` or `ListComprehension` part of the java code (see the traceback). And this profile accounts for a few megabytes of memory usage, when it OOM at more that 14 GBytes in my computer.

**Comment by aherrmann** [comment]
@guibou Just to be sure, did you control the JVM heap size by setting `--host_jvm_args=-Xmx`? AFAIK by default it will not use up all of the machine's RAM. If not, maybe bumping the heap size allows to get a heap profile on a larger use-case to pin down the source of the OOM.

I'm surprised that `ln` is on the top of this list. Are those numbers cumulative? That would explain the large number, as we call `ln()` a lot. However, I doubt it would cause an OOM as we don't create all these symlinks at once.

**Comment by Profpatsch** [comment]
@guibou still a problem?

**Comment by guibou** [comment]
Not anymore since a few bazel upgrade.
